- INSTALL.md
- README.md
- docs/assets/ofrak_gui_1.png
- docs/getting-started.md
- docs/index.md
- ofrak_tutorial/Dockerstub
- ofrak_tutorial/Makefile
This is just some introductory text to make the GUI frontend more visible in the README and docs.
Next PR should probably a slightly deeper dive into the OFRAK gui.
> Docs/frontend (introductory)

- INSTALL.md
- disassemblers/ofrak_ghidra/setup.py
- ofrak_core/setup.py
> add explicit requirements on PyYAML

- INSTALL.md
closes #18 
Adding an optional space to the serial regex seems to fix the issue for me
N/A
> account for space in Binary Ninja license.dat file

- examples/ex2_simple_code_modification.py
- examples/ex5_binary_extension.py
- examples/ex7_code_insertion_with_extension.py
No open issues
Corrects dependency imports/discovery.
@EdwardLarson
> Fix capstone imports.

- .github/workflows/test-all.yml
- frontend/Makefile
N/A
Run the frontend linting as a CI pipeline step in the linting job.
@whyitfor
> Add frontend linting to CI

- .github/workflows/test-all.yml
- frontend/Makefile
- frontend/package.json
- frontend/src/ofrak/remote_resource.js
N/A
A previous PR (#44) doesn't actually cause the CI pipeline to fail when there are linter errors. This PR fixes that issue.
@whyitfor
> Fail CI when frontend linting fails

- ofrak_core/setup.py
Addresses https://github.com/lief-project/LIEF/issues/763.
See https://github.com/lief-project/LIEF/blob/master/doc/sphinx/changelog.rst for full list of changes.
Bump lief to 0.12.2
> Bump lief to 0.12.2

- mkdocs.yml
N/A
1. Update title for docs to be "OFRAK Docs" (as a disambiguation from ofrak.com homepage).
2. Change docs font to Barlow.
> Update OFRAK Docs title to OFRAK Docs, change font to Barlow

- ofrak_core/test_ofrak/components/test_architecture_analysis.py
N/A.
This PR adds a test for `MemoryRegionProgramAttributesAnalyzer`.
> Add a test for MemoryRegionProgramAttributesAnalyzer.

- ofrak_core/ofrak/service/resource_service.py
> Update typehints for ResourceAttributeIndex

- ofrak_components/ofrak_components/strings_analyzer.py
- ofrak_components/ofrak_components_test/test_strings_analyzer.py
Add test for strings_analyzer to get 100% function coverage
> Test coverage strings

- disassemblers/ofrak_angr/Makefile
- disassemblers/ofrak_angr/ofrak_angr/model.py
- disassemblers/ofrak_binary_ninja/Makefile
- disassemblers/ofrak_binary_ninja/ofrak_binary_ninja/components/identifiers.py
- Delete BinaryNinjaAnalysisResource.get_binaryninja_analysis
- Delete AngrAnalysisResource.get_angr_analysis
> Removed unused disassembler analysis methods

- frontend/src/App.svelte
- frontend/src/ResourceTreeNode.svelte
- frontend/src/ResourceTreeView.svelte
- frontend/src/SearchView.svelte
- frontend/src/StartView.svelte
N/A
An update to the linter is breaking the CI pipeline by raising new linter errors in the frontend. This applies the fixes from the updated linter.
@EdwardLarson
> Lint using latest version of linter

- disassemblers/ofrak_angr/setup.py
- disassemblers/ofrak_binary_ninja/setup.py
- disassemblers/ofrak_capstone/setup.py
- disassemblers/ofrak_ghidra/Makefile
- disassemblers/ofrak_ghidra/setup.py
- ofrak_components/setup.py
- ofrak_core/Makefile
- ofrak_core/setup.py
- ofrak_io/setup.py
- ofrak_patch_maker/Makefile
- ofrak_patch_maker/setup.py
- ofrak_tutorial/setup.py
- ofrak_type/setup.py
> Bump fun-coverage to 0.1.3

- frontend/backend/ofrak_server.py
- ofrak_core/ofrak/resource.py
Use the `Resource.identify` interface in the OFRAK server.
> Use Resource.identify interface in OFRAK server

- examples/ex6_code_modification_without_extension.py
- ofrak_patch_maker/ofrak_patch_maker/patch_maker.py
- ofrak_patch_maker/ofrak_patch_maker_test/test_toolchain_asm.py
https://github.com/redballoonsecurity/ofrak/pull/122
Replace usage of inject_patch with SegmentInjectorModifier
@EdwardLarson @whyitfor
> Deprecate usage of inject_patch.

- frontend/backend/ofrak_server.py
- frontend/src/App.svelte
- frontend/src/BinaryModifyView.svelte
- frontend/src/ModifyView.svelte
- frontend/src/ResourceTreeToolbar.svelte
- frontend/src/helpers.js
- frontend/src/ofrak/remote_resource.js
- frontend/src/ofrak/resource.js
- ofrak_core/ofrak/service/dependency_handler.py
N/A
Until the hex view becomes a hex editor, this pull request enables a user to perform arbitrary binary modifications in the GUI.
@whyitfor
> Support arbitrary binary modification in the GUI

- ofrak_type/CHANGELOG.md
- ofrak_type/ofrak_type/architecture.py
N/A
Adds enum for ARM A55 SoC.
> Adds Cortex A55 to ProcessorType enum.

- README.md
- disassemblers/ofrak_capstone/README.md
- docs/index.md
- ofrak_core/README.md
- ofrak_io/README.md
- ofrak_patch_maker/README.md
- ofrak_type/README.md
Update information about commercial licenses in READMEs,.
> Update package README information about licenses.

- docs/user-guide/angr.md
- docs/user-guide/gotchas.md
- mkdocs.yml
> Added angr and PIE docs

- docs/user-guide/patch-maker/user-guide.md
- ofrak_core/ofrak/core/patch_maker/modifiers.py
Minor edits to PatchMaker documentation to ensure it matches ofrak-patch-maker 2.0.0 API.
@andresito00
> Update documentation to correctly reflect ofrak-patch-maker 2.0.0 API.

- ofrak_core/CHANGELOG.md
- ofrak_core/Dockerstub
- ofrak_core/ofrak/core/ubi.py
- ofrak_core/ofrak/core/ubifs.py
- ofrak_core/setup.py
- ofrak_patch_maker/CHANGELOG.md
- ofrak_patch_maker/setup.py
- ofrak_type/CHANGELOG.md
- ofrak_type/setup.py
Release ofrak 2.1.0, ofrak_patch_maker 3.0.0, and ofrak_type 2.1.0
> Release Candidate: ofrak 2.1.0

- ofrak-core-dev.yml
- ofrak_core/CHANGELOG.md
- ofrak_core/ofrak/service/data_service.py
- ofrak_core/pytest_ofrak/utils.py
- ofrak_core/test_ofrak/service/data_service/conftest.py
- ofrak_core/test_ofrak/service/data_service/data_service_interface_test.py
Fix bug in data service that can cause mangled internal state.
The internal data structure that the DataService uses to identify data models affected by a patch was not properly updated in some cases. This could cause strange errors down the line.
* Fix bugs in DataService
* Add a class decorator to make debugging internal state of service etc. easier.
@whyitfor
> Bugfix: data service internal state

- frontend/package.json
- frontend/src/App.svelte
- frontend/src/JumpToOffset.svelte
- ofrak_core/CHANGELOG.md
- ofrak_core/setup.py
> increment ofrak_core version number

- frontend/src/App.svelte
- frontend/src/HexView.svelte
- ofrak_core/CHANGELOG.md
Show mapped resource captions on hover in the hex view.
@whyitfor
> Use resource captions for tooltip in hex view

- ofrak_core/test_ofrak/components/free_space_components_test/test_allocatable_allocate.py
remove dependency on ofrak_patch_maker_test
Unnecessary import of `ofrak_patch_maker_test` necessitated installing that package to run ofrak_core tests
Just write out the same source code to disk and use that.
> remove dependency on ofrak_patch_maker_test

- docs/user-guide/advanced/flash_component.md
Fix link in Flash docs page.
N/A
Link was broken, now unbroken.
> Fix link in Flash docs

- ofrak_core/ofrak/gui/server.py
Fixed sorting issue where sections without data were missing from gui.
N/A
Added a custom sort function that sorts children by data offset if existent, and otherwise places children without data at the end of the list.
@rbs-jacob
> Fix get_children sorting so that sections without Data are not missing 

- ofrak_patch_maker/Dockerstub
- ofrak_patch_maker/ofrak_patch_maker/toolchain.conf
- ofrak_patch_maker/ofrak_patch_maker/toolchain/abstract.py
- ofrak_patch_maker/ofrak_patch_maker/toolchain/gnu.py
- ofrak_patch_maker/ofrak_patch_maker/toolchain/gnu_ppc.py
- ofrak_patch_maker/ofrak_patch_maker_test/example_2/bom1.ppc.S
- ofrak_patch_maker/ofrak_patch_maker_test/example_2/bom2.ppc.S
- ofrak_patch_maker/ofrak_patch_maker_test/example_2/bom3.ppc.S
- ofrak_patch_maker/ofrak_patch_maker_test/test_ppc_toolchain.py
Add PPC GNU 10 Linux toolchain support to OFRAK PatchMaker. Addresses #204.
@andresito00
> Add PPC GNU 10 Linux toolchain (fix #204)

- ofrak_core/requirements-docs.txt
N/A
The way the version req was written was easy to cause version requirement conflicts
Write the version requirement to be clear and should still function as intended
> remove 6.0 version req for pyyaml

- frontend/package.json
- frontend/src/AddTagView.svelte
- frontend/src/StartView.svelte
- frontend/src/ofrak/remote_resource.js
- frontend/src/stores.js
In `ofrak/frontend` webserver, add option to change the backend url in `stores.js`
> Add option to change backend URL in stores.js

- disassemblers/ofrak_binary_ninja/README.md
- docs/user-guide/disassembler-backends/binary_ninja.md
Update the docs for how to install and run OFRAK Binary Ninja locally.
#270 
Documentation changes
@whyitfor
> Add documentation for running Binja natively

- disassemblers/ofrak_angr/Makefile
- disassemblers/ofrak_binary_ninja/Makefile
- disassemblers/ofrak_capstone/Makefile
- disassemblers/ofrak_ghidra/Makefile
- docs/contributor-guide/getting-started.md
- ofrak_core/Makefile
- ofrak_io/Makefile
- ofrak_patch_maker/Makefile
- ofrak_type/Makefile
Update Contributor Guide with information and static code analysis
- Specify what static code analysis is performed on repository and its packages
- Document structure of an OFRAK package Makefile
- Remove unneeded dependencies, clean Makefile targets
> Update Contributor Guide with information and static code analysis

- mkdocs.yml
Docs copyright notice extends through 2023.
> Update OFRAK Docs copyright to include 2023

- frontend/public/global.css
- frontend/src/App.svelte
- frontend/src/BinaryModifyView.svelte
- frontend/src/ComponentsView.svelte
- frontend/src/FindReplaceView.svelte
- frontend/src/ResourceTreeNode.svelte
- frontend/src/ResourceTreeToolbar.svelte
- frontend/src/RunScriptView.svelte
- frontend/src/SettingsView.svelte
- frontend/src/stores.js
> Highlight fix

- frontend/src/Gamepad.svelte
> add null check for gamepad

- frontend/src/RunScriptView.svelte
No changelog entry required since this was fixed in a feature that has not yet been released.
@EdwardLarson
> Fix undefined variable bug in run script view

- ofrak_core/ofrak/core/ihex.py
Bugfix in Intel Hex identifier to avoid regex matching the entire file. 
N/A.
- Update IhexIdentifier to use "max_matches" to only find first match
- Update regex to match on pattern of 2 valid ihex lines at beginning of file
These changes avoid matching on entire contents of a file encoded in Intel Hex format, making identification run faster.
@EdwardLarson
> Update IhexIdentifier to only search for one match.

- frontend/src/ProjectManager/ProjectManagerCheckbox.svelte
- frontend/src/ProjectManager/ProjectManagerView.svelte
- frontend/src/ResourceTreeToolbar.svelte
- frontend/src/RunScriptView.svelte
Associated scripts checkboxes do not persist through changes in selected binary, and will appear in run script option. 
@Edward-Larson
> Fix inclusive script checkboxes

- ofrak_core/Dockerstub
- ofrak_core/requirements.txt
- ofrak_core/setup.py
Add dependency on GitPython to requirements.txt. Was added to Docker build, but not python package requirements.
> update python requirements with GitPython

- disassemblers/ofrak_binary_ninja/install_binary_ninja_headless_linux.sh
- disassemblers/ofrak_ghidra/ofrak_ghidra/components/ghidra_analyzer.py
- disassemblers/ofrak_ghidra/ofrak_ghidra/config/ofrak_ghidra.conf.yml.default
- disassemblers/ofrak_ghidra/ofrak_ghidra/config/ofrak_ghidra_config.py
- disassemblers/ofrak_ghidra/ofrak_ghidra/constants.py
- disassemblers/ofrak_ghidra/ofrak_ghidra/ghidra_scripts/GetCodeRegions.java
- disassemblers/ofrak_ghidra/ofrak_ghidra/ghidra_scripts/GetComplexBlocks.java
- disassemblers/ofrak_ghidra/ofrak_ghidra/run_ghidra_server.sh
- disassemblers/ofrak_ghidra/ofrak_ghidra_test/assets/example_ghidra_package/example_ghidra_package.py
- disassemblers/ofrak_ghidra/ofrak_ghidra_test/assets/example_ghidra_package/ghidra_scripts/GetCodeRegionsDuplicate.java
- disassemblers/ofrak_ghidra/ofrak_ghidra_test/test_additional_script_dirs.py
- disassemblers/ofrak_ghidra/ofrak_ghidra_test/test_ghidra_config.py
- disassemblers/ofrak_ghidra/ofrak_ghidra_test/test_ghidra_server.py
Fix shell expansion bug with headless Ghidra invocation, and make sure Binja installation script uses Python3 
> Bugfix: ghidra binja reliability

- frontend/src/ProjectManager/ProjectManagerBinaryOptions.svelte
- frontend/src/ProjectManager/ProjectManagerOptions.svelte
- frontend/src/ProjectManager/ProjectManagerScriptOptions.svelte
- frontend/src/ProjectManager/ProjectManagerView.svelte
- frontend/src/ResourceTreeView.svelte
- frontend/src/ScriptView.svelte
- frontend/src/utils/Script.svelte
> Refactor ScriptView.svelte into generic component for use in OFRAK Projects 

- frontend/src/ResourceTreeToolbar.svelte
- frontend/src/StartView.svelte
- ofrak_core/ofrak/gui/server.py
- ofrak_core/ofrak/project/project.py
- ofrak_core/test_ofrak/unit/test_ofrak_server.py
> Better support switching between project view and resource view. 

- ofrak_core/CHANGELOG.md
- ofrak_core/requirements.txt
> bump GitPython to 3.1.35

- frontend/.prettierignore
- frontend/src/resource/ResourceTreeToolbar.svelte
- ofrak_core/CHANGELOG.md
Fix bug in frontend "Replace" button. Before it was appending new data instead of replacing it as intended.
@whyitfor @dannyp303
> Fix bug in front end "Replace" button

- ofrak_patch_maker/CHANGELOG.md
- ofrak_patch_maker/Dockerstub
- ofrak_patch_maker/ofrak_patch_maker/toolchain.conf
- ofrak_patch_maker/ofrak_patch_maker/toolchain/gnu_x86.py
- ofrak_patch_maker/ofrak_patch_maker_test/test_x86_toolchain.py
- ofrak_patch_maker/ofrak_patch_maker_test/toolchain_c.py
Add x86 32-bit GNU toolchain
**To Do**
@whyitfor
> Add x86 32-bit GNU toolchain

- frontend/src/views/ComponentsView.svelte
- frontend/src/views/RunScriptView.svelte
- frontend/src/views/StartView.svelte
- ofrak_core/ofrak/gui/server.py
Fix GUI drag & drop functionality
#406 
Also fix bug with running scripts without a project selected, and when running components whose config is explicitly set to "None". 
And, sorts components in RunComponentsView drop-down alphabetically.
@whyitfor
> Bugfix: gui drag n drop

- frontend/src/ofrak/remote_resource.js
- frontend/src/ofrak/resource.js
- frontend/src/resource/ResourceTreeToolbar.svelte
- frontend/src/views/StartView.svelte
- ofrak_core/CHANGELOG.md
- ofrak_core/ofrak/gui/server.py
- ofrak_core/test_ofrak/unit/test_ofrak_server.py
Add identify recursively to the GUI.
> Add identify recursively to the GUI

- ofrak_core/requirements.txt
Bump orjson to ~=3.9.15.
See https://github.com/redballoonsecurity/ofrak/security/dependabot/19.
See above.
No.
> Update orjson to ~=3.9.15 to address security issue.

- frontend/src/hex/HexView.svelte
> reduce chunking min limit from 64mb to 1mb

- disassemblers/ofrak_angr/CHANGELOG.md
- disassemblers/ofrak_angr/requirements.txt
Update to latest angr==9.2.93
N/A
Update to latest angr==9.2.93
@whyitfor and/or @SamL98?
> Update angr to a more recent 9.2.93

- frontend/src/hex/HexView.svelte
> Fix bug where minimap doesn't appear on big files. 

- .github/workflows/test-all.yml
- frontend/.gitignore
- frontend/package-lock.json
> Add `package-lock.json` to version control and use `npm ci` for consistent frontend dependencies. Fixes #493

- .github/workflows/test-all.yml
#532 
In #532 I pinned the Ubuntu version for only one of the CI jobs. This PR fixes my silly mistake and applies the change to all of the CI jobs.
@whyitfor
> Pin Ubuntu version (but actually this time)

- ofrak_core/CHANGELOG.md
- ofrak_core/ofrak/core/free_space.py
- ofrak_core/setup.py
[#504](https://github.com/redballoonsecurity/ofrak/issues/504)
@whyitfor
> Add docstrings and ensure valid range

- ofrak_core/setup.py
- ofrak_type/CHANGELOG.md
- ofrak_type/setup.py
**One sentence summary of this PR**
Bump `ofrak_core` and `ofrak_type` release candidate versions. Update `ofrak_type` CHANGELOG.
Resolve threads in #581.
> Bump ofrak_core and ofrak_type rc versions

- ofrak_core/CHANGELOG.md
- ofrak_core/requirements.txt
Pin orjson to fix test failures
[Tests in Actions workflow failing on `master`](https://github.com/redballoonsecurity/ofrak/actions/runs/14733877920/job/41358220972#step:6:546) as of the [release of `orjson==3.10.17` a few hours ago](https://pypi.org/project/orjson/3.10.17/).
> Pin orjson to fix test failures

- .github/workflows/test-all.yml
Cache LFS objects in GitHub Actions to reduce LFS bandwidth usage from testing.
> Cache LFS objects in GitHub Actions

- ofrak_tutorial/CHANGELOG.md
- ofrak_tutorial/notebooks_with_outputs/3_binary_format_modification.ipynb
- ofrak_tutorial/setup.py
Tests running on different machines had different elf offsets in notebook 3 outputs. This MR makes the notebook output more generic so that this is not an issue.
N/A.
See above.
No.
> Refactor tutorial 3 output to be less brittle

- ofrak_type/CHANGELOG.md
- ofrak_type/ofrak_type/range.py
- ofrak_type/ofrak_type_test/test_bitwidth.py
- ofrak_type/ofrak_type_test/test_endianness.py
- ofrak_type/ofrak_type_test/test_memory_permissions.py
- ofrak_type/ofrak_type_test/test_range.py
Added some tests in ofrak_type, added error checking in `range.py`
- Added tests to `ofrak_type_test`
- Added error checking in `range.py`
No
> Added some tests, added some error checking in range.py

- frontend/package.json
- frontend/src/App.svelte
- ofrak_core/CHANGELOG.md
- ofrak_core/ofrak/gui/server.py
- ofrak_core/setup.py
Display filename for files loaded in GUI
N/A
Add a File atttribute to every file loaded in the OFRAK GUI so that the filename appears.
@rbs-jacob
> Display filename for files loaded in GUI

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.svelte
- ofrak_core/CHANGELOG.md
- ofrak_core/ofrak/core/entropy/entropy.py
- ofrak_core/ofrak/core/entropy/entropy_c.py
- ofrak_core/setup.py
- ofrak_core/test_ofrak/components/test_entropy_component.py
Fixed import error when entropy c library is not found
@whyitfor
> fix dependency injector import error

- .github/workflows/publish-to-test-pypi.yml
Merging to enable manual triggering.
> Add publish-to-test-pypi.yml
