redballoonsecurity/ofrak

ofrak_components/ofrak_components_test/test_gzip_component.py

$ `flake8 . --count --select=E9,F63,F7,F82,Y --show-source --statistics`
```
./ofrak_components/ofrak_components_test/test_gzip_component.py:84:24: F821 undefined name 'result'
data = result.stdout
^
./ofrak_core/ofrak/core/patch_maker/linkable_binary.py:150:22: F821 undefined name 'PatchMaker'
patch_maker: "PatchMaker",  # type: ignore
^
./ofrak_core/ofrak/service/error.py:55:49: F821 undefined name 'DataNode'
def __init__(self, message, new_child_node: "DataNode", existing_child_node: "DataNode"):  # type: ignores
^
./ofrak_core/ofrak/service/error.py:55:82: F821 undefined name 'DataNode'
def __init__(self, message, new_child_node: "DataNode", existing_child_node: "DataNode"):  # type: ignore
^
4     F821 undefined name 'result'
4
```

Fix undefined name result

---

INSTALL.md

Installers will appreciate 6 steps instead of 12…
```bash
brew install apktool binwalk cmake java libmagic lzop p7zip qemu squashfs rar unar wget
```

INSTALL.md: Streamline macOS installation

---

ofrak_components/Dockerstub

Issue #10 
This version bump includes [squashfs-tools commit f151730a83e92cbea00eda8f70e9039e145054a9 : "Unsquashfs: don't use max open file limit if larger than caches"](https://github.com/plougher/squashfs-tools/commit/f151730a83e92cbea00eda8f70e9039e145054a9). It was created to address https://github.com/plougher/squashfs-tools/issues/125 which I believe is related to #10. This change fixes the error present and allows the tutorial image to run without issue.

Bumped squashfs-tools to 4.5.1

---

ofrak_core/ofrak/core/elf/lief_modifier.py
ofrak_core/ofrak/core/elf/model.py
ofrak_core/test_ofrak/components/test_patch_maker_component.py
ofrak_patch_maker/Dockerstub
ofrak_patch_maker/ofrak_patch_maker/toolchain/abstract.py
ofrak_patch_maker/ofrak_patch_maker/toolchain/gnu.py
ofrak_patch_maker/ofrak_patch_maker/toolchain/utils.py
ofrak_patch_maker/ofrak_patch_maker/toolchain/version.py
ofrak_patch_maker/ofrak_patch_maker_test/__init__.py
ofrak_patch_maker/ofrak_patch_maker_test/test_toolchain_c.py
ofrak_patch_maker/toolchain.conf

This PR adds PatchMaker and toolchain support for the AVR architecture. Needed to fix a few assumptions, for example, some compiler/linker flags set in `Abstract_GNU_Toolchain` are not supported in `avr-gcc`. Additionally, the `LiefAddSegmentModifier` relied on an existing NOTE segment, which AVR ELFs do not have. I've added a configuration option to choose between NOTE replacement vs LIEF's add segment method.

PatchMaker support for AVR

---

.github/workflows/test-all.yml
build_image.py

N/A
PR #27 added a GitHub CI pipeline. This pull request fixes some minor issues with the pipeline and adds some minor improvements. Specifically:
- Use `pv` when doing `docker load` and `docker save` so there is a logged progress bar
- Run the pipeline on merges with `master`, not just pull requests
- Add an optional input to force flushing the Docker image cache on manual workflow runs
- Fix a small bug in `build_image.py` when no `--cache-from` arguments are passed
@whyitfor

Fix CI pipeline bugs

---

.github/workflows/test-all.yml
ofrak_tutorial/notebooks_with_outputs/6_code_insertion_with_extension.ipynb

N/A
The CI pipeline is currently blocked by failure to convert some of the tutorial Jupyter notebooks. This, in turn, is because an [update to `nbformat`](https://pypi.org/project/nbformat/5.5.0/#history) (on which the Jupyter notebook package depends) no longer accepts cells without IDs. 
This PR fixes this issue by giving all of the cells in tutorial notebook 6 IDs. For some weird reason, that was the only notebook without them. 
The fixed notebook was generated by opening the broken notebook in the web interface, running all cells, and exporting the resulting notebook as an `.ipynb`. 
@whyitfor

Fix lack of IDs in tutorial notebook 6

---

build_image.py

N/A
The `# syntax` line in a `Dockerfile` must be the first line. This change fixes the generated `Dockerfile` such that this is the case. This, in turn, fixes errors when building the image with a mounted Binary Ninja license.
@whyitfor

Put the `Dockerfile` syntax line at the top

---

ofrak_core/setup.py

https://github.com/redballoonsecurity/ofrak/security/dependabot/1
https://github.com/redballoonsecurity/ofrak/security/dependabot/2
https://github.com/redballoonsecurity/ofrak/security/dependabot/3
https://github.com/redballoonsecurity/ofrak/security/dependabot/4
Bump lief version to 0.12.1 to mitigate the above-referenced security issues in older versions of lief. 
@jstrieb

Bump lief to 0.12.1

---

build_image.py

N/A
In OFRAK Docker image builds that have many packages, we are hitting the maximum layer depth allowed by Docker. This PR condenses many separate layers (that are rarely cached) in the "finish" image into one layer.
I tried to further condense the "finish" image by having all of the `ADD` lines in `finish.Dockerfile` be combined into one big `ADD`, but it doesn't actually look like that's possible to cleanly do. The problem is that, as it is now, each `ADD` command specifically writes to a destination directory it must create. Thus, writing everything to `/` doesn't create those directories. Rather, it dumps the contents of those directories into the root directory. See:
- …

Use fewer layers in the "finish" Dockerfile

---

disassemblers/ofrak_angr/Makefile
disassemblers/ofrak_binary_ninja/Makefile
disassemblers/ofrak_capstone/Makefile
disassemblers/ofrak_ghidra/Makefile
ofrak_components/Makefile
ofrak_core/Makefile
ofrak_patch_maker/Makefile

N/A.
This change enforces function coverage for Python libraries in this repository. Specifically, it ensures that the current level of function coverage is the baseline: the tests will fail if function coverage dips below this line.
@EdwardLarson

Add function coverage targets for OFRAK packages

---

docs/user-guide/flash_component.md
examples/ex9_flash_modification.py
mkdocs.yml

Adds a documentation page explaining why and how to use the NAND flash component. Includes the accompanying link in the navigation menu. An example is also included.
@whyitfor @andresito00

Add flash component documentation and example

---

ofrak_core/ofrak/core/filesystem.py

Closes #60 
Adds validation of the path parameter passed to `FilesystemRoot.initialize_from_disk`. Will raise a `FileNotFoundError` if the path is not found or is to a file instead of a directory.
@whyitfor since they opened the issue

FilesystemRoot.initialize_from_disk path validation

---

ofrak_core/Makefile
ofrak_core/test_ofrak/unit/test_ofrak_context.py

N/A
Adds a unit test for `OFRAK.run` method. This raises `ofrak` function coverage to 79%.

Add a test for OFRAK.run.

---

disassemblers/ofrak_angr/ofrak_angr/serializer.py
disassemblers/ofrak_angr/ofrak_angr_test/test_serializer.py
frontend/Makefile
frontend/backend/ofrak_server.Dockerfile
frontend/backend/ofrak_server.py

N/A
* Add an option to set Angr as the disassembler backend when starting the GUI
* Instead of Ghidra being the default backend if none is provided, no backend is used (no disassembly is possible, but this allows the GUI server to be run in an image/install that only has core OFRAK + frontend with no extra dependencies).
* Add a serializer class to "catch" the Angr analysis object so that it is not erroneously serialized when communicating with the frontend. This serializer doesn't actually correctly serialize the object, but instead always serializes it to `None` and raises a hard error on deserializing, as saving disassembler backend metadata is not currently supported.
* A few updates/improvements for the GUI …

Angr in GUI

---

ofrak_core/test_ofrak/components/test_pe_component.py

N/A
Increase function test coverage for Pe resource views to 100.
- test PeSectionHeader.get_flags
- test Program.get_memory_region_for_vaddr returns the correct MemoryRegion
- refactor test resource generation code
No.

Add tests for Pe resource views

---

frontend/package.json
frontend/src/AttributesView.svelte
frontend/src/ResourceTreeToolbar.svelte
frontend/src/ofrak/resource.js

This updates paths for CommentsAttributes and Magic in frontend to reflect the fact that they are in `ofrak.core`.
The incorrect path was causing the `CommentsAttributes` to not appear in the frontend tree view as intended.
I tested these changes by building the tutorial image and validating that the comments were appearing in the resource tree view.
@rbs-jacob

Update paths for CommentsAttributes and Magic to match their new location

---

build_image.py
frontend/Dockerstub
ofrak-dev.yml
ofrak-ghidra.yml
ofrak-tutorial.yml
ofrak_tutorial/Dockerstub

Some Dockerstubs defined ENTRYPOINTs which were confusing to track down and could overwrite each other.
This adds an optional field to our OFRAK Docker build config for the entrypoint of the finished image. This way, when you build an image it is very clear what the entrypoint will be.
@rbs-jacob

move ENTRYPOINT definition out of Dockerstubs and into build YAML

---

ofrak_core/Dockerstub
ofrak_patch_maker/Dockerstub

These changes support M1 for only core functionality and does not include backend support from Ghidra/Binja.

Changed x86 specific binaries and options for M1 support

---

.gitattributes
docs/user-guide/gui/assets/image1.png
docs/user-guide/gui/assets/image2.png
docs/user-guide/gui/assets/image25.png
docs/user-guide/gui/assets/image3.png
docs/user-guide/gui/assets/image4.png
docs/user-guide/gui/assets/image5.png
docs/user-guide/gui/assets/image6.png
docs/user-guide/gui/assets/image7.png
docs/user-guide/gui/minimap.md
mkdocs.yml

N/A
This pull request adds documentation for the minimap portion of the GUI frontend, and sets up a folder in the docs directory for future documenting of the GUI.
@whyitfor

Add GUI minimap explanation to the OFRAK docs

---

docs/user-guide/flash_component.md
ofrak_components/setup.py
ofrak_core/ofrak/resource.py
ofrak_core/ofrak/service/resource_service_i.py
ofrak_core/setup.py

- Bump mkdocs to 1.2.3, as 1.2.2 is exposed to GHSA-qh9q-34h6-hcv9
- Update broken links in NAND Flash Components documentation
- Update Resource docstrings which reference parameters removed in #40
- Update ResourceServiceInterface docstrings which reference parameters deprecated in #40
@EdwardLarson

Bump mkdocs to 1.2.3, address misc. errors in OFRAK Docs

---

ofrak_io/.coveragerc
ofrak_io/ofrak_io_test/test_batch_manager.py
ofrak_io/setup.py

This removes an unnecessary dependency on ofrak for ofrak_io tests. The BatchManagerInterface and implementations can be tested without reliance on ofrak classes.
This also adds a .coveragerc file for ofrak_io, which excludes abstractmethods from line and function coverage, resulting in deleting unneeded tests.
@EdwardLarson

Remove ofrak_io[test] dependency on ofrak

---

ofrak_components/Makefile
ofrak_components/ofrak_components/lzma.py

Because of the way that fun-coverage detects function coverage, this was a refactor. A test for that function already existed.

LZMA function coverage to 100%

---

ofrak_core/ofrak/service/serialization/serializers/__init__.py
ofrak_core/setup.py

- Make beartype an ofrak package requirement, since it is used by serializers.
- Suppress BeartypeDecorHintPep585DeprecationWarning (pending resolution of #92) so that users can focus on ofrak without getting these error messages.
Closes #91.
#91 
No.

Move beartype from test requirement to ofrak package requirement

---

ofrak_components/Makefile
ofrak_components/ofrak_components/ecc/reedsolomon.py
ofrak_components/ofrak_components/entropy/entropy.py
ofrak_components/ofrak_components/openwrt.py

- Remove unused `ReedSolomon.check` method
- Skip entropy helper functions that are run by the DataSummaryAnalyzer in an executor (pycoverage does not seem to see them running; they are not part of OFRAK API)
- Remove unused `OpenWrtTrxHeader.get_length` method
Improves function coverage for `ofrak_components` package from 84 to 88

Improve function coverage of ofrak_components from 84 to 88

---

ofrak_components/Makefile
ofrak_components/ofrak_components_test/test_dtb_component.py

Getting DTB property path with property.get_path() and asserting correct path

Upping test coverage for DTB component to 100%

---

ofrak_components/Makefile
ofrak_components/ofrak_components/iso9660.py
ofrak_components/ofrak_components_test/test_iso_component.py

There was a bug with `ISO9660Image.get_file()` that led to refactoring away `ISO9660EntryAttributes` into `ISO9660Entry`.

Write tests for ISO9660 component for 100% function coverage

---

ofrak_core/Makefile
ofrak_core/ofrak/core/filesystem.py
ofrak_core/test_ofrak/components/test_filesystem_component.py

Fix a bug in Folder.get_entry implementation, add test coverage for FilesystemRoot, File, Folder.
This PR brings filesystem resource view function coverage to 100%, and overall ofrak function coverage to 93%.
@EdwardLarson

Add test coverage of Filesystem methods

---

ofrak_components/Makefile
ofrak_components/ofrak_components/uimage.py
ofrak_components/ofrak_components_test/test_uimage_component.py

- Add tests for UImageHeader, UImageMultiHeader
- Add UImage.get_multi_header method
Bump ofrak_components test function coverage to 99

Add tests for UImageHeader, UImageMultiHeader

---

disassemblers/ofrak_capstone/ofrak_capstone/components.py
ofrak_core/ofrak/ofrak_context.py
ofrak_core/ofrak/resource.py
ofrak_core/ofrak/service/data_service.py
ofrak_core/pytest_ofrak/patterns/code_region_unpacker.py
ofrak_core/pytest_ofrak/patterns/unpack_verify.py
ofrak_core/test_ofrak/service/data_service/data_service_interface_test.py
ofrak_core/test_ofrak/unit/test_resource.py

There were two subtle bugs in the new DataService not caught by the data service tests, both having to do with mapped data models: Shifts to consecutive mappings were not updated properly when applying a resizing patch to the entirety of a mapped model, and the get_data_range_within_other did not correctly translate the returned range when comparing two mapped ranges.
* Bugfixes for the two issues described above
* Test cases for those two issues as well
* Add an optional function to the CodeRegionUnpacker tests which is now allowed to be unpacked since it has overlaps
Wyatt or Jacob, I expect Wyatt has more time in this case

Bugfix: Fixes for subtle errors as a result of new Data Service

---

ofrak_components/Makefile
ofrak_components/ofrak_components/flash.py
ofrak_components/ofrak_components_test/test_flash_component.py
ofrak_core/test_ofrak/components/assets/flash_test_magic.bin
ofrak_core/test_ofrak/components/assets/flash_test_magic_verify.bin

Added a test file with MAGIC in the tail block and it's _verify binary.
Found a bug in the untested function that would not find the magic in the tail block. The offset was incremented to early in the while loop which would scan one byte too far to unpack the block and therefore fail.
Finally, bumped function coverage for ofrak_components to 100%

Add test coverage for all functions in flash component

---

ofrak_core/Dockerstub
ofrak_core/setup.py

- Remove keystone-engine install from source for ofrak Docker image
- pin keystone-engine to 0.9.2

Use keystone-engine==0.9.2

---

.github/workflows/test-all.yml
disassemblers/ofrak_capstone/Dockerstub
disassemblers/ofrak_capstone/Makefile
disassemblers/ofrak_capstone/ofrak_capstone/disassembler_service_capstone.py
disassemblers/ofrak_capstone/ofrak_capstone_test/test_ofrak_capstone.py
disassemblers/ofrak_capstone/setup.py

- Use capstone==4.0.2 from pypi, remove unneeded install from source in Dockerstub
- Update TestCapstoneRegisterUsage.case_is_known_broken, as "cmp byte ptr [0x600880], 0x0" is correctly handled by capstone==4.0.2
- Add test_capstone_analyzer to trigger CapstoneInstructionAnalzer to run
- Update Makefile to enforce 100 function coverage for ofrak_capstone
- Run capstone tests with angr tests in CI
@EdwardLarson

Switch to using capstone 4.0.2

---

ofrak_core/Makefile
ofrak_core/ofrak/model/resource_model.py
ofrak_core/ofrak/ofrak_context.py
ofrak_core/test_ofrak/unit/test_resource_model.py

- Remove unused methods from resource_model.py: __get_leaves, ResourceModel.{get_specific_tags, to_diff, to_model}
- Use ClientResourceContextFactory to instantiate ResourceFactory in OFRAKContext
- Add tests for ResourceIndexedAttribute.{__set__, __getattr__, __repr__}
- Add test for ResourceAttributes.__str__
Function test coverage for ofrak bumps from 93 to 94

Prune resource_model.py, increase test coverage

---

ofrak_core/ofrak/model/viewable_tag_model.py
ofrak_core/ofrak/resource.py

Remove Resource.get_offset_within_root
- Remove Resource.get_offest_within_root, an unused method which was originally removed in #69
- Make abstract methods of ResourceViewInterface as such

Resource.get_offest_within_root

---

ofrak_components/ofrak_components/zip.py

N/A
The ZIP unpacker changes the working directory to the temporary directory, but does not need to. Sometimes the temporary directory it tries to change to is not valid, and this raises an exception. 
This PR removes the working directory change and removes the possibility of that exception being raised.
@EdwardLarson

Remove unnecessary working directory changes in ZIP unpacker

---

docs/environment-setup.md

- Removed custom keystone/capstone install instructions (they were deprecated with #100 and #101)
- Remove cmake from Mac install list, as it is no longer needed
- Add install instructions for binwalk from GitHub repo
@rbs-jacob

Update OFRAK Environment Setup instructions:

---

ofrak_core/ofrak/resource.py
ofrak_core/test_ofrak/unit/resource_view/test_view.py

A subtle bug that could cause some confusion. Usually, when a resource is modified by a component, when those modifications are fetched to the local context the views of that resource are updated (i.e. their fields may change if those values were changed in the resource). However, if one makes a modification locally to a resource then calls .save(), those changes are not applied to the local views.
When `save()` is called on a resource, update the views. A small change is made to the internal method `Resource._update_views` to make this cleaner.
@whyitfor

Update views of a resource when .save() is called on it

---

ofrak_core/ofrak/component/abstract.py

If a config is not provided to a component, the default component is pulled from the components relevant method (`identify`, `analyze`, etc.) using the `inspect` library. This was being done every time a component runs and was found to inflict a somewhat significant performance penalty (~8%) for no added benefit.
The default config is extracted once, when the component is initialized.
@rbs-jacob

cache component's default configs

---

ofrak_core/ofrak/core/free_space.py
ofrak_core/ofrak/resource.py
ofrak_core/test_ofrak/unit/test_resource.py

This change makes the data and data_range arguments to `Resource.create_child` mutually exclusive. This change tightens and simplifies the `create_child` API to support 3 uses:
1. If data is provided, an unmapped child is created
2. If data_range is provided, a mapped child is created
3. If neither are provided, a dataless child is created
`FreeSpaceModifier` is also updated to account for this change.
@andresito00  and @EdwardLarson

Resource.create_child takes either data or data_range argument

---

disassemblers/ofrak_angr/setup.py
disassemblers/ofrak_binary_ninja/setup.py
disassemblers/ofrak_capstone/setup.py
disassemblers/ofrak_ghidra/setup.py
ofrak_components/ofrak_components/uf2.py
ofrak_components/setup.py
ofrak_core/Makefile
ofrak_core/setup.py
ofrak_io/setup.py
ofrak_patch_maker/Makefile
ofrak_patch_maker/setup.py
ofrak_tutorial/setup.py
ofrak_type/setup.py

fun-coverage 0.1.3 was incorrectly excluding all functions with decorators from coverage results. 
Bump fun-coverage to 0.1.4.

Bump fun-coverage to 0.1.4

---

disassemblers/ofrak_capstone/ofrak_capstone/components.py
frontend/src/ofrak/resource.js
ofrak_core/ofrak/core/elf/modifier.py
ofrak_core/ofrak/core/patch_maker/modifiers.py
ofrak_core/ofrak/resource.py

For some cases of large resource trees, the overhead from managing async becomes a large portion of the runtime. One of the "hot" areas of code is the view creation method, which involves lots of async calls and gathers which are not always necessary.
* non-async check for up-to-date attrs before calling analyze in create_view
* remove `Resource.analyze_attributes` method (redundant with `Resource.analyze`)
* Create a non-async private method that returns a view if possible, and an awaitable to get the view if creating the view synchronously is not possible.
@whyitfor

More efficient view_as with less async overhead

---

ofrak_core/ofrak/core/free_space.py
ofrak_core/test_ofrak/components/test_free_space.py

Refactor `PartialFreeSpaceModifier` to ensure that free range lies within the target resource rage.
The PR also refactors `PartialFreeSpaceModifier` to comply with `Resource.create_child` interface as of #130, and adds a test for the modifier.
@andresito00

Update PartialFreeSpaceModifier to use create_child correctly, add test

---

ofrak_core/Makefile
ofrak_core/ofrak/core/elf/modifier.py

- Remove unused ElfModifierUtils. YAGNI!
- Refactor ElfPointerArraySectionAddModifier to remove unused method
Bump function coverage back to 96.

Remove unused (and untested) ElfModifierUtils

---

ofrak_core/ofrak/core/memory_region.py
ofrak_core/ofrak/service/error.py

Remove `OverlapError`. Since #40, this is no longer an error raised by the data service.
@EdwardLarson

Remove OverlapError, as it is no longer required

---

disassemblers/ofrak_angr/setup.py
disassemblers/ofrak_binary_ninja/setup.py
disassemblers/ofrak_capstone/setup.py
disassemblers/ofrak_ghidra/setup.py
ofrak_components/setup.py
ofrak_core/Makefile
ofrak_core/ofrak/model/resource_model.py
ofrak_core/ofrak/model/viewable_tag_model.py
ofrak_core/setup.py
ofrak_io/setup.py
ofrak_patch_maker/setup.py
ofrak_tutorial/setup.py
ofrak_type/setup.py

- Bump fun-coverage to 0.2.0
- Fix signature of function in resource_model.py
- Mark all methods of ResourceViewInterface as no cover (one was missed in #111)
- Bump ofrak function coverage to 97

Several improvements to ofrak test coverage

---

disassemblers/ofrak_angr/ofrak_angr/components/blocks/unpackers.py
disassemblers/ofrak_binary_ninja/ofrak_binary_ninja/components/blocks/unpackers.py
ofrak_core/ofrak/core/memory_region.py
ofrak_core/test_ofrak/components/test_memory_region.py

- Remove MemoryOverlapError (and its error handling). Like OverlapError(#144), this error is never raised
- Add unit tests for `MemoryRegion.{__str__, __hash__}`
@EdwardLarson

Remove MemoryOverlapError

---

ofrak_core/ofrak/core/architecture.py
ofrak_core/ofrak/core/free_space.py
ofrak_core/ofrak/ofrak_context.py
ofrak_core/setup.py
ofrak_core/test_ofrak/components/free_space_components_test/test_allocatable_allocate.py
ofrak_patch_maker/ofrak_patch_maker/model.py
ofrak_patch_maker/ofrak_patch_maker/patch_maker.py
ofrak_patch_maker/ofrak_patch_maker/toolchain/abstract.py
ofrak_patch_maker/ofrak_patch_maker/toolchain/gnu.py
ofrak_patch_maker/ofrak_patch_maker/toolchain/llvm_12.py
ofrak_patch_maker/ofrak_patch_maker/toolchain/vbcc_gnu_hybrid.py
ofrak_patch_maker/ofrak_patch_maker_test/__init__.py
ofrak_patch_maker/ofrak_patch_maker_test/test_aarch64_toolchain.py
ofrak_patch_maker/ofrak_patch_maker_test/test_arm_toolchain.py
ofrak_patch_maker/ofrak_patch_maker_test/test_avr_toolchain.py
ofrak_patch_maker/ofrak_patch_maker_test/test_m68k_toolchain.py
ofrak_patch_maker/ofrak_patch_maker_test/test_x86_toolchain.py
ofrak_patch_maker/ofrak_patch_maker_test/toolchain_asm.py
ofrak_patch_maker/ofrak_patch_maker_test/toolchain_c.py
ofrak_tutorial/notebooks_with_outputs/6_code_insertion_with_extension.ipynb
ofrak_type/ofrak_type/__init__.py
ofrak_type/ofrak_type/architecture.py

`ofrak_patch_maker`'s dependency on OFRAK created a circular dependency. This wasn't necessarily problematic as pip handled it gracefully, but it did preclude a "lightweight" patch maker install without OFRAK.
Things were moved/refactored so that `ofrak_patch_maker` doesn't import from `ofrak`.
* `ProgramAttributes` gets a superclass `ArchInfo` defined in `ofrak_type` so that we don't rely on a `ResourceAttributes` for just grouping arch information
* The `BOM` and `AssembledObject` get some additional fields to include enough information that we don't need to call out to a `Toolchain` after creation - required BSS size and alignment, specifically
* The `get_required_alignment` method in `Toolchain` is also …

Decouple patch maker from ofrak

---

.dockerignore
.github/workflows/test-all.yml
examples/Dockerstub
examples/Makefile
examples/ex2_simple_code_modification.py
examples/ex5_binary_extension.py
examples/ex6_code_modification_without_extension.py
examples/ex7_code_insertion_with_extension.py
ofrak-tutorial.yml

Refactor example scripts to use Ghidra. Test these examples in CI.
Note that this PR is possible because of #139. Examples 5 and 7 have to account for the discrepancy between the PIE-Elf addresses and the virtual addresses supplied by Ghidra. A more elegant solution, which would not need this workaround, is beyond the scope of this PR: for now, it is advantageous to be able to run the examples in CI and have users run them with publicly available software (examples previously used Binary Ninja backend).
@SamL98, FYI. @EdwardLarson

Use Ghidra exclusively for examples, test that examples work in CI

---

frontend/src/Checkbox.svelte
frontend/src/FindReplaceView.svelte
frontend/src/SearchView.svelte

N/A
Previously, inconsistently-styled, native checkboxes were used for boolean inputs in the GUI. This PR adds custom, cross-browser, cross-platform, consistently-styled checkbox components.
Before:
After:
@EdwardLarson

Add cross-browser checkbox component

---

ofrak_core/ofrak/core/filesystem.py

Unpacking very large filesystems can be extremely slow. This pull request makes it considerably faster by removing an unnecessary `resource.save` from the `add_file` function in the OFRAK core filesystem functions. 
Run the following code before and after the change to compare the improvement.
``` bash
pushd /tmp
mkdir -p test
for i in {1..50000}; do
echo "${i}" > "test/${i}.txt"
done
zip -9 -r test.zip test/
python3 <<EOF
import logging
from ofrak import OFRAK
async def main(context):
root = await context.create_root_resource_from_file("./test.zip")
await root.unpack()
ofrak = OFRAK(logging.INFO)
ofrak.run(main)
EOF
popd
```
On my system, the original code takes 420 seconds to run this benchmark, and the updated code in this pull request …

Remove unnecessary, slow resource.save

---

disassemblers/ofrak_angr/ofrak_angr/components/angr_analyzer.py
disassemblers/ofrak_angr/ofrak_angr/components/blocks/unpackers.py

Uses PIE detection for ELF's to fixup the virtual address of CodeRegion's. Support for other filetypes (PE, Mach-O, etc.) should be added as needed.

PIE support for Angr

---

ofrak_core/ofrak/core/free_space.py
ofrak_patch_maker/CHANGELOG.md

N/A
Adds a new parameter to `allocate_bom` which specifies possible destination permissions for the current patch segment.
i.e. Developers can specify that .rodata segments of patches may be stored in the .text section of programs.
@EdwardLarson @whyitfor

Enables permission re-mapping from patch to destination program 

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/__main__.py
ofrak_core/ofrak/cli/command/gui.py
ofrak_core/ofrak/cli/command/identify.py
ofrak_core/ofrak/cli/command/unpack.py
ofrak_core/ofrak/cli/ofrak_cli.py
ofrak_core/ofrak/gui/server.py
ofrak_core/ofrak/ofrak_context.py
ofrak_core/setup.py
ofrak_core/test_ofrak/unit/test_ofrak_cli.py
ofrak_core/test_ofrak/unit/test_ofrak_context.py

Add APIs to open GUI in a script or after CLI commands complete.
* Add flags to open GUI after `inject` or `unpack` completes
* Add `-r` flag to `unpack` command, to unpack recursively
* Add `get_current_ofrak_context` which... gets the current OFRAK context, so this can be done in any arbitrary place in a script or component and one doesn't have to keep passing the context around. It uses a global variable for this and is therefore fairly brittle, and would break if two contexts are created concurrently. I added a check and error raise for this so it won't be a silent bug.
* Add `open_gui` function to simply start the server and open a …

APIs to integrate GUI more deeply into OFRAK workflows

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/patch_maker/modifiers.py

The same way we do with the .got section, ignore .rela sections in patch maker FEM while injecting.

Ignore .rela sections in FEM created by placeholder

---

frontend/src/App.svelte
frontend/src/AssemblyView.svelte
frontend/src/ResourceTreeToolbar.svelte
frontend/src/helpers.js
ofrak_core/CHANGELOG.md
ofrak_core/setup.py

GUI uses correct attribute class names again (not *AutoAttributes)
We changed the name scheme for auto-generated attributes classes, and the GUI was still in some cases trying to use the old names, which caused errors.
Update the names used in the GUI appropriately.

rename references to AutoAttributes in frontend

---

ofrak-core-dev.yml

Fix error installing `ofrak-core-dev.yaml` configuration build
No open issues that I found but the error I received:
```
$ python3 build_image.py --config ofrak-core-dev.yml --base --finish
...
...
...
make -C ofrak_core develop
make[1]: Entering directory '/ofrak_core'
if [ -d /ofrak_gui ] ; then \
cp -r /ofrak_gui ofrak/gui/public ; \
else \
pushd ../frontend ; \
npm run build ; \
popd ; \
cp -r ../frontend/public ofrak/gui/public ; \
fi
/bin/sh: 4: pushd: not found
/bin/sh: 5: npm: not found
/bin/sh: 6: popd: not found
cp: cannot stat '../frontend/public': No such file or directory
make[1]: Leaving directory '/ofrak_core'
make[1]: *** [Makefile:25: ofrak/gui/public] Error 1
make: *** …
```

Fix issue installing ofrak-core-dev configuration

---

disassemblers/ofrak_binary_ninja/Dockerstub
disassemblers/ofrak_binary_ninja/pin_version.py
docs/environment-setup.md
docs/user-guide/binary_ninja.md
docs/user-guide/patch-maker/user-guide.md
ofrak-binary-ninja.yml

Pin BinaryNinja version to 3.2.3814 in Docker build.
Pin BinaryNinja version to 3.2.3814. This is currently the recommended BinaryNinja version for compatibility with OFRAK.

Pin BinaryNinja version to 3.2.3814.

---

frontend/public/sounds/Bush+Week.mp3
frontend/public/sounds/Dream+Sunlight.mp3
frontend/public/sounds/Glimmer.mp3
frontend/public/sounds/Motion+Blur.mp3
frontend/public/sounds/Panthalassa.mp3
frontend/scripts/download-music.sh
frontend/src/App.svelte
frontend/src/AudioPlayer.svelte

Remove music files and player.
The music files were huge, and took up the majority of space in the `pip` package. Also auto-playing music is obnoxious. 
This PR removes the music files from the repo (and thereby from the built frontend, and thus from `pip`), and only opens the audio player as an easter egg, once per year. Hopefully this strikes a good balance between maintaining fun energy and not being bothersome.
@EdwardLarson

Remove music files

---

ofrak-core-dev.yml
ofrak_core/CHANGELOG.md
ofrak_core/ofrak/cli/command/gui.py
ofrak_core/ofrak/cli/command/identify.py
ofrak_core/ofrak/cli/command/unpack.py
ofrak_core/ofrak/gui/server.py

Enable running the GUI without opening the browser.
Sometimes, a user may not want to open the browser automatically when they start the GUI. This adds a command-line option to enable that feature.
@EdwardLarson

Enable running the GUI without opening the browser

---

frontend/src/App.svelte
frontend/src/JumpToOffset.svelte
ofrak_core/CHANGELOG.md

Add a GUI input to jump to a given data offset.
This PR adds a bit of text above the minimap in the hex view that shows the current file offset. Clicking this text will allow the user to edit it and set it arbitrarily. Doing so and either defocusing the input or pressing "Enter" will apply the change and jump within the file. 
Note that the calculator is enabled such that calculations can also be performed in this quick jump box. For example, a user could enter something like `0x10 * 5 + 0xdeadbeef`, and it would work.
The resulting change looks like this:
@EdwardLarson

Add input to jump to offset

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/component/abstract.py
ofrak_core/ofrak/core/patch_maker/modifiers.py
ofrak_core/ofrak/resource.py
ofrak_core/ofrak/service/dependency_handler.py
ofrak_core/ofrak/service/resource_service.py
ofrak_core/test_ofrak/components/test_patch_maker_component.py

Delete narrower list of resources when injecting.
All descendants of the injected resource itself would be deleted when injecting segments, not just the descendants affected. The injected resource itself was of course modified, and all descendants of modified resources were marked to be deleted.
Only delete resources which are descendants, modified, AND not the injected resource.
@whyitfor @rbs-afflitto

Bugfix: more selective criteria for resources to delete when injecting

---

frontend/package.json
frontend/src/FileBrowser.svelte
frontend/src/StartView.svelte
frontend/src/TextDivider.svelte
frontend/src/helpers.js
ofrak_core/CHANGELOG.md

This adds a "file browser" dialog component to the GUI.
This PR adds a "file browser" to the GUI and places it on the first screen when the GUI loads. This PR also includes a few small changes such as a warning for large files and a new default message when there are no previously-loaded resources for the start page dropdown.
The new start page looks like this:
@whyitfor

Add GUI file dialog component

---

ofrak-dev.yml

N/A
Trivial bugfix - `ofrak-dev.yml` container build was failing otherwise, so I copied the `license.dat` lines from `ofrak-binary-ninja.yml`, and now it works.
@EdwardLarson maybe?

Fix a dev container build failure

---

ofrak_core/Makefile

Make `make -C ofrak_core develop` more robust:
- Make it work when `/bin/sh` is `dash` and does not have `pushd`/`popd`
- Make it work when there is no `frontend` (such as in the `ofrak-minimal` container)
@jstrieb

Fix `ofrak-minimal` build, make `make -C ofrak_core develop` more robust

---

frontend/src/ResourceTreeNode.svelte
frontend/src/StartView.svelte
ofrak_core/CHANGELOG.md

Fix bug where initially loaded GUI resource has collapsed children.
When loading a resource in the GUI via `ofrak unpack` or `ofrak identify` at the command line, the initially-loaded resource would have its children collapsed. This change set fixes that issue.
@EdwardLarson

Set initially loaded resource to "uncollapsed"

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/flash.py
ofrak_core/test_ofrak/components/assets/flash_test_default_unpacked_modified_verify.bin
ofrak_core/test_ofrak/components/assets/flash_test_default_unpacked_verify.bin
ofrak_core/test_ofrak/components/test_flash_component.py

Allows for multiple of the same `FlashField.field_type` within a block format as described by `FlashAttributes`
N/A
Instead of assuming only one of type DATA or ECC, now will parse each field individually and handle accordingly. This should allow a lot more flexibility to customize for different use cases.
@whyitfor

Add support for flash with multiple of the same field type in attribute

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/service/job_service.py
ofrak_core/test_ofrak/components/test_elf_analyzers.py
ofrak_core/test_ofrak/components/test_tar_component.py
ofrak_core/test_ofrak/unit/test_resource.py

the component's error is now at the bottom of the stack trace, so the user sees it first
Tweak how errors are raised when auto-running components, so the actual root cause is not buried
If a component is auto-run (which is common, every `analyze` or `unpack` are auto-runs for example) and it raises an error `E`, then the job service also generates it's own error `F` with info about why the component was chosen by the auto-run. Previously the errors were raised as `raise F from E`, which resulted in the stack trace printing error info in the order:
```
E
F
```
So what a user sees most obviously is some junk about the auto-run, and the root cause is buried halfway up. This also translates to …

swap order that errors are raised when auto-running fails

---

ofrak_core/requirements.txt

re-pin xattr version to version that works with Python 3.9
The xattr version we had pinned it to used a filter for classifiers in its setup.py, and Python 3.9 needs to that be a list, so installing that version of xattr raises an error in Python 3.9.
Re-pin to latest version of xattr
@whyitfor

re-pin xattr version to version that works with Python 3.9

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/elf/model.py

Add a caption to ElfProgramHeader.
This is a small quality-of-life improvement for the GUI:

Add captions for ElfProgramHeader

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/__init__.py
ofrak_core/ofrak/gui/server.py
ofrak_core/ofrak/model/resource_model.py
ofrak_core/ofrak/resource.py
ofrak_core/ofrak/service/dependency_handler.py
ofrak_core/test_ofrak/service/dependency_handler/test_dependency_handler.py
ofrak_core/test_ofrak/unit/test_data_attributes.py

Add mechanism to sort & filter by data length or offset like other indexable attributes (e.g. VirtualAddress)
There wasn't a way to format a query (like `get_descendants`) so that OFRAK would filter or sort by aspects of the resource's binary data. Users would have to grab that info themselves and implement some filtering or sorting logic locally.
* Add `RootOffset` and `Length` indexable attributes that can be used to sort of filter by these aspects of resource's binary data:
`r_sort=ResourceSort(RootOffset),`
* Have the GUI sort resources by data offset by default
* Implement this with a semi-magical special ResourceAttributes known as …

Sort by data {length, offset}

---

frontend/src/ResourceTreeNode.svelte
frontend/src/ofrak/remote_resource.js

Force resource caption refresh in the GUI tree.
Previously, running components in the GUI might update a resource's caption, but this change would not be reflected in the tree. This PR fixes that bug by forcing the caption to refresh when a resource's children refresh, which happens every time the resource changes.
@EdwardLarson

Force resource caption refresh in the GUI tree

---

frontend/src/App.svelte
ofrak_core/CHANGELOG.md

Add current resource caption to GUI browser tab title.
This small PR improves the OFRAK GUI user's experience by adding the current resource caption to the tab title. This makes it much more convenient to have different OFRAK GUI windows open simultaneously, since a user no longer has to guess which tab or window has which resource. 
@whyitfor

Change tab title to include the current caption

---

frontend/src/ResourceTreeNode.svelte

The bugfix from #225 did fix the intended bug (resource tree captions not updating), but in doing so, makes one additional request for each child resource. This PR addresses the original bug without making those extra requests.
@whyitfor @EdwardLarson

Update tree caption with fewer requests

---

docs/user-guide/advanced/patch-maker/user-guide.md

Alas, PyCharm is a more forgiving renderer of Markdown than MkDocs :(
This minor fix improves the rendering of a bulleted list in the PatchMaker docs. Specifically, it turns [this](https://ofrak.com/docs/user-guide/advanced/patch-maker/user-guide.html#patchmaker-steps):
into this:
@andresito00

Fix bulleted list in PatchMaker docs

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/cli/command/deps.py
ofrak_core/ofrak/core/apk.py
ofrak_core/ofrak/core/binwalk.py
ofrak_core/ofrak/core/cpio.py
ofrak_core/ofrak/core/gzip.py
ofrak_core/ofrak/core/lzo.py
ofrak_core/ofrak/core/rar.py
ofrak_core/ofrak/core/seven_zip.py
ofrak_core/ofrak/core/squashfs.py
ofrak_core/ofrak/core/tar.py
ofrak_core/ofrak/core/ubi.py
ofrak_core/ofrak/core/ubifs.py
ofrak_core/ofrak/core/zip.py
ofrak_core/ofrak/core/zstd.py
ofrak_core/ofrak/model/component_model.py
ofrak_core/ofrak/ofrak_context.py
ofrak_core/test_ofrak/unit/component/test_component_external_tool.py

Use `asyncio.create_subprocess_exec`instead of blocking subprocess.run calls in packers/unpackers.
#53 
See above
@rbs-jacob

Use `asyncio.create_subprocess` instead of `subprocess.run`

---

disassemblers/ofrak_angr/MANIFEST.in
disassemblers/ofrak_capstone/MANIFEST.in
disassemblers/ofrak_ghidra/MANIFEST.in
ofrak_core/CHANGELOG.md
ofrak_core/MANIFEST.in
ofrak_core/ofrak/ofrak_context.py
ofrak_core/requirements.txt
ofrak_patch_maker/MANIFEST.in
ofrak_tutorial/MANIFEST.in

N/A
* Libmagic was missing on windows, so not even importing `python-magic` worked
* requirements.txt files were not part of pip packages, so setup.py could not find and parse them
* /tmp/ofrak.log is not a valid path on Windows
*  install libmagic binaries on windows
* include requirements files in packages
* get log file in OS-agnostic way

Maintenance: Windows pip install

---

frontend/src/HexView.svelte
frontend/src/JumpToOffset.svelte
ofrak_core/CHANGELOG.md

The GUI "jump to offset" feature would round up to nearest 16-byte-aligned address. This fixes this behavior to correctly round down.
See above.

Fix bug in GUI where "jump to offset" 

---

disassemblers/ofrak_ghidra/requirements.txt
frontend/package.json
frontend/src/App.svelte
ofrak_core/CHANGELOG.md
ofrak_core/Dockerstub
ofrak_core/ofrak/core/apk.py
ofrak_core/requirements-test.txt
ofrak_core/requirements.txt
ofrak_core/setup.py

Update OFRAK to 2.2.1
Bump version numbers, plus minor touch-ups:
* remove pyyaml 6.0 pin in ofrak_ghidra
* handle missing uber-apk-signer properly and os-agnostic
* dockerstub goes to tmp dir with absolute path

Release/ofrak 2.2.1

---

ofrak_patch_maker/CHANGELOG.md
ofrak_patch_maker/ofrak_patch_maker/toolchain/gnu.py

Adding the -fno-pic compiler flag to the GNU Toolchain allows non-relocatable arm64 patches to succeed
N/A
This pull request adds the -fno-pic compiler flag to the GNU Toolchain
@whyitfor

Adding necessary compiler flags for non-relocatable arm64 patches

---

docs/environment-setup.md
mkdocs.yml

Fix path to GUI keybindings in OFRAK docs, and another broken link in the docs.

Fix path to GUI keybindings in OFRAK documentation

---

frontend/src/JumpToOffset.svelte
ofrak_core/CHANGELOG.md

Fix bug where jumping to a multiple of `0x10` in the GUI went to the previous line.
The changes introduced in #243 caused a different bug where jumping to an exact multiple of `0x10` rounded down the address to jump to and went to the previous line in the hex view of the GUI. This change fixes that issue.
@whyitfor

Fix bug when jumping to a multiple of 0x10

---

ofrak_core/Dockerstub

Add `cmake` to `ofrak_core/Dockerstub`.
`cmake` is needed for some Python packages that need to be built. For example, keystone on M1 (see https://github.com/redballoonsecurity/ofrak/issues/76#issuecomment-1416160037).
Add `cmake` to `ofrak_core/Dockerstub`.

Add cmake to ofrak_core Dockerstub file

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/cli/command/gui.py

Add option to `ofrak gui` to pre-load some files into OFRAK before opening the GUI, so they can be explore right away
The `ofrak gui` command didn't have a way to open a file in the GUI. It was easy to work around with `ofrak identify --gui` which will take a file and then open the GUI, but it wasn't obvious. It just made it a bit clumsier to transition from a terminal to using the GUI.
Add the "--file" (or "-f") argument to pass paths to files. Multiple files can be passed in this way, and the the user can choose one from the dropdown menu on the home screen.
@whyitfor I believe you …

add argument for `ofrak gui` command to load files as Resources

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/model/component_filters.py
ofrak_core/ofrak/model/job_request_model.py
ofrak_core/ofrak/resource.py
ofrak_core/ofrak/service/job_service.py
ofrak_core/test_ofrak/service/component_locator/test_component_locator.py

Choose Analyzer components which output the entirety of a view, rather than piece by piece, which would choose the wrong Analyzer sometimes.
ResourceViews are composed of multiple attributes types, and when running something like `view_as` OFRAK would previously make a request for each of those attributes types. With limited visibility into what the user actually wants, the job service would sometimes end up choosing Analyzers which do output one or more of the requested attributes but actually require the analysis of the other attributes, resulting in a deadlock.
* Auto-analyze attributes requests now can take multiple attributes types at …

Better view analysis

---

ofrak_patch_maker/CHANGELOG.md
ofrak_patch_maker/ofrak_patch_maker/toolchain/abstract.py
ofrak_patch_maker/ofrak_patch_maker/toolchain/gnu.py
ofrak_patch_maker/ofrak_patch_maker/toolchain/llvm_12.py
ofrak_patch_maker/ofrak_patch_maker/toolchain/model.py

- Add separate data sections support to LLVM toolchain, and add general flag for including subsections
Extends and replaces https://github.com/redballoonsecurity/ofrak/pull/203
The addition of the `separate_data_sections` functionality to the LLVM toolchain aligns it with the GNU toolchain. In both toolchains, enabling `separate_data_sections` requires broadening the pattern for the sections we keep from the BOM to the FEM. Per the discussion in #203, I added a separate flag that just enables that broader keep list without actually making data sections.

General support for separate_data_sections, and new flag for keeping more sections

---

.github/pull_request_template.md

Add language to the PR template about the OFRAK contributor guide.
Happy to change the language to whatever people think is best, but having a link to the contributor guide front-and-center would be helpful.
@whyitfor

Draft PR contributor guide link language

---

ofrak_core/test_ofrak/unit/test_ofrak_server.py

Previously, `test_create_mapped_child` could fail randomly if the first result in `unpack` was a resource without data to carve. This PR uses the first result of `get_children` instead, which is now deterministically ordered, so the test should no longer attempt to carve a resource without data.
N/A
Call `create_mapped_child` on results of `get_children` instead of `unpack`.
@whyitfor  @rbs-jacob

Fix `test_create_mapped_child`

---

ofrak_core/test_ofrak/unit/test_ofrak_server.py

Compare scripts as strings rather than lists, and remove parts of the strings which may change frequently or be inconsistent across runs (error messages, including the resource IDs within those messages).
#279 
Add a function that joins scripts as lists into one string and then replace the error messages with a constant value.
@rbs-jacob @whyitfor

Normalize GUI script strings before testing

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/uf2.py
ofrak_core/test_ofrak/components/test_uf2_component.py

UF2 file identification was not working. This PR fixes this, and updates the tests to specifically test that identifcation works.
- Add a Magic Mime identifier for UF2 files
- Deletes custom Uf2FileIdentifier which was not working
- Updates UF2 tests with a test to assert that identification works
- Update UF2 unpack test to remove adding Uf2File tag (this was making the test pass even though the identifier wasn't working)
@sjossi

Fix UF2 file identification so that it works

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/apk.py
ofrak_core/ofrak/core/squashfs.py
ofrak_core/ofrak/model/component_model.py
ofrak_core/test_ofrak/unit/component/test_component_external_tool.py

- [ x] I have reviewed the [OFRAK contributor guide](https://ofrak.com/docs/contributor-guide/getting-started.html) and attest that this pull request is in accordance with it.
Fix bug where Component External Tool would raise an error when checking whether a tool was installed returned a non-zero exit value 
N/A
Remove checks against returncode in subprocess calls for `is_tool_installed` methods that would raise a `CalledProcessError`.
Add test case to check return value of `is_tool_installed` when attempting to check for tool with known bad flag that will return non-zero exit code. …

Remove CalledProcessError from `is_tool_installed`

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/cpio.py
ofrak_core/ofrak/core/filesystem.py
ofrak_core/test_ofrak/components/assets/filesystem.cpio
ofrak_core/test_ofrak/components/test_cpio_component.py

Reverts redballoonsecurity/ofrak#276
Found a significant behavior divergence in the 7zz unpacker: Symbolic links are no longer unpacked.

Revert "Update CPIO unpacker to use 7z utility instead of cpio utility issue …"

---

ofrak-dev.yml
ofrak-ghidra.yml
ofrak_core/ofrak/cli/ofrak_cli.py

Specify disassembler backend for OFRAK GUI in yaml files and modify import logic.
#292 
Added flag to specify the `ghidra` backend when starting up the OFRAK GUI in the Docker container yaml files. Additionally, adjusted the import logic to fix an issue where name collisions were resulting in an exception being raised when a directory of the same name as the intended package existed in the working directory.
@whyitfor @EdwardLarson @rbs-jacob

Specify disassembler backend when starting GUI in container

---

frontend/src/ByteclassView.svelte
frontend/src/EntropyView.svelte
frontend/src/MagnitudeView.svelte
ofrak_core/CHANGELOG.md

Sometimes clicking "Unpack" or "Identify" (for example) too quickly after loading a large resource causes an error that freezes up the whole GUI. This fixes that problem.
@EdwardLarson

Fix freezes from undefined image data

---

ofrak_core/ofrak/core/elf/analyzer.py
ofrak_core/ofrak/core/elf/model.py
ofrak_core/ofrak/core/elf/unpacker.py
ofrak_core/test_ofrak/components/test_elf_analyzers.py
ofrak_tutorial/notebooks_with_outputs/2_ofrak_internals.ipynb

Refactor ELF components to remove UnanalyzedElfSection, UnanalyzedElfSegment.
- These two ResourceViews are not needed, and do not add value to the user.
See above.
@EdwardLarson

Remove UnanalyzedElfSection, UnanalyzedElfSegment

---

disassemblers/ofrak_binary_ninja/install_binary_ninja_headless_linux.sh

Remove linux-setup.sh from BinaryNinja headless install steps.
The linux-setup.sh step was not working; it is not actually needed for a headless install of BinaryNinja in Docker.
It was therefore removed.
I've tested the change and validated the OFRAK BinaryNinja tests pass in the built Docker image.
@EdwardLarson

Remove linux-setup.sh step from BinaryNinja headless install

---

ofrak_core/ofrak/core/elf/analyzer.py
ofrak_core/ofrak/gui/server.py
ofrak_core/ofrak/ofrak_context.py
ofrak_core/test_ofrak/unit/test_ofrak_context.py
ofrak_core/test_ofrak/unit/test_ofrak_server.py

Previously the GUI backend server used an `OFRAKEnvironment` object to get the list of components offered to the user to run. However this includes components from all installed OFRAK packages, including ones that weren't discovered as part of spinning up the server. So if the user selected one of these components, they would get an error. 
Additionally, if an OFRAK package was installed without all of its dependencies, any import errors could be avoided by not importing/discovering the package. However since getting the component list through the `OFRAKEnvironment` always imports all installed modules, a user could not avoid getting import errors for such installed, incomplete, and …

Bugfix: Only list discovered components in the GUI

---

disassemblers/ofrak_ghidra/ofrak_ghidra/components/ghidra_analyzer.py

Minor bugfix: detect when Ghidra client dies unexpectedly
N/A
If the Ghidra headless client dies unexpectedly, `ghidra_proc.stdout.readline()` in `GhidraProjectAnalyzer._do_ghidra_import` keeps returning an empty string, and the `white True:` would keep spinning forever. This change catches this scenario.
Just for context, I hit this issue with
```
[ghidra_analyzer.py:  139] Started ghidra import.: 619
User home directory does not exist: ?
User home directory does not exist: ?
User home directory does not exist: ?
[ghidra_analyzer.py:  145] 
[ghidra_analyzer.py:  145] Failed to find a supported JDK.  Please refer to the Ghidra Installation …
```

Minor bugfix: detect when Ghidra client dies unexpectedly

---

frontend/src/App.svelte
frontend/src/Gamepad.svelte
ofrak_core/CHANGELOG.md

Add DDR pad support to the OFRAK GUI. Only maps buttons on the pad to keyboard shortcut callbacks – some more work is required to handle combos. 
@EdwardLarson

Add initial USB DDR pad support to the GUI

---

frontend/src/Pane.svelte
ofrak_core/CHANGELOG.md

Fix minimap bottom overlapping version number.
@EdwardLarson

Fix minimap bottom overlapping version number

---

frontend/src/HexView.svelte
frontend/src/StartView.svelte
frontend/src/TextView.svelte

Fix three small bugs:
- Prevent the dropdown on the GUI StartView from getting too wide
- Make sure the text view contents actually update when the data changes
- The hex view no longer takes a while to load, and thus no longer needs a loading animation – having the animation was initializing and destroying OpenGL contexts on every scroll, which was expensive and wasteful. Now it shows the text "Loading" without animation
@EdwardLarson

Slim the GUI start view dropdown and fix TextView update bug

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/elf/analyzer.py
ofrak_core/ofrak/core/elf/model.py
ofrak_core/ofrak/core/strings.py
ofrak_core/ofrak/resource.py
ofrak_core/ofrak/service/data_service.py
ofrak_core/ofrak/service/data_service_i.py
ofrak_core/test_ofrak/service/data_service/data_service_interface_test.py

Add method to Resource and data service to search for patterns in its data
Previously the only way to search was to request all the data then search it. This copying of data is inefficient, and searching for patterns in data is something users are likely to be interested in, so this makes sense to add to the API.
- Add a `search` method to the data service that allows searching for either literal bytes or a regex pattern
- Add a `search_data` method to Resource which calls the DataService's `search` method on itself

Data service search

---

disassemblers/ofrak_ghidra/ofrak_ghidra/components/ghidra_analyzer.py
disassemblers/ofrak_ghidra/ofrak_ghidra/config/ofrak_ghidra.conf.yml.default
disassemblers/ofrak_ghidra/ofrak_ghidra/config/ofrak_ghidra_config.py
disassemblers/ofrak_ghidra/ofrak_ghidra/constants.py
disassemblers/ofrak_ghidra/ofrak_ghidra/ghidra_scripts/CreateRepository.java
disassemblers/ofrak_ghidra/ofrak_ghidra/run_ghidra_server.sh
disassemblers/ofrak_ghidra/ofrak_ghidra/server/__main__.py
disassemblers/ofrak_ghidra/ofrak_ghidra_test/test_ghidra_config.py
disassemblers/ofrak_ghidra/ofrak_ghidra_test/test_ghidra_server.py

Actually use the fields of the ofrak_ghidra.config when setting up the ghidra repository
Basically we had infrastructure to configure ofrak for a local ghidra setup, but the ofrak_ghidra code was not looking at that config at all.

Bugfix: use ghidra config

---

ofrak_core/ofrak/core/extfs.py
ofrak_core/test_ofrak/components/assets/ext2.1024.img
ofrak_core/test_ofrak/components/assets/ext2.2048.img
ofrak_core/test_ofrak/components/assets/ext2.4096.img
ofrak_core/test_ofrak/components/assets/ext3.1024.img
ofrak_core/test_ofrak/components/assets/ext3.2048.img
ofrak_core/test_ofrak/components/assets/ext3.4096.img
ofrak_core/test_ofrak/components/assets/ext4.1024.img
ofrak_core/test_ofrak/components/assets/ext4.2048.img
ofrak_core/test_ofrak/components/assets/ext4.4096.img
ofrak_core/test_ofrak/components/test_extfs_component.py

Add packers and unpackers for EXT filesystems (versions 2 through 4).
@whyitfor @EdwardLarson 
**Outstanding tasks:**

EXT Filesystem Components

---

build_image.py
ofrak_core/Dockerstub
ofrak_core/ofrak/core/ihex.py
ofrak_core/requirements-non-pypi.txt
ofrak_core/requirements.txt
ofrak_core/setup.py

I added the bincopy dependency to the requirements.txt as a github link, but it turns out that blocks PyPI:
>ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
> ofrak depends on bincopy@ git+https://github.com/eerimoq/bincopy.git@17.14.5
So I've moved bincopy (and binwalk) into a `requirements-non-pypi.txt`, and a pip extras rule for them under "non-pypi", which is installed in the `build-image.py`. I also added the necessary ComponentExternalTool and protections in the ihex components which use `bincopy`.

isolate non-python dependencies

---

frontend/src/ResourceTreeNode.svelte
frontend/src/ResourceTreeView.svelte

Fixed bug in resource node searchbar that would ignore the last keypress before searchQuery == none
OFRAK-620
Properly use and implement searchResult instead of searchFilter in node searchbar. 
@Edward-Larson

Searchbar delete bug

---

ofrak_core/ofrak/ofrak_context.py
ofrak_core/ofrak/resource.py
ofrak_core/test_ofrak/unit/test_ofrak_context.py

Add new method to OFRAKContext that will create a new FilesystemRoot and all of its children from a directory path. 

create root resource from directory

---

mkdocs.yml

Fix GUI docs nav bar URLs. Right now they 404.
@dannyp303

Fix GUI docs URLs in nav bar

---

CONTRIBUTING.md
examples/ex1_simple_string_modification.py
examples/ex2_simple_code_modification.py
examples/ex3_binary_format_modification.py
examples/ex4_filesystem_modification.py
examples/ex5_binary_extension.py
examples/ex6_code_modification_without_extension.py
examples/ex7_code_insertion_with_extension.py
examples/ex8_recursive_unpacking.py
examples/ex9_flash_modification.py
ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/elf/load_alignment_modifier.py
ofrak_core/ofrak/core/filesystem.py
ofrak_core/ofrak/core/ubi.py
ofrak_core/ofrak/resource.py
ofrak_core/test_ofrak/components/test_elf_modifiers.py
ofrak_core/test_ofrak/components/test_patch_from_source.py
ofrak_core/test_ofrak/components/test_patch_maker_component.py
ofrak_core/test_ofrak/unit/test_resource.py
ofrak_tutorial/notebooks_with_outputs/1_simple_string_modification.ipynb
ofrak_tutorial/notebooks_with_outputs/3_binary_format_modification.ipynb
ofrak_tutorial/notebooks_with_outputs/4_simple_code_modification.ipynb
ofrak_tutorial/notebooks_with_outputs/5_filesystem_modification.ipynb
ofrak_tutorial/notebooks_with_outputs/6_code_insertion_with_extension.ipynb

Better flushing of files to disk.
#362 
- Add `FilesystemEntry.flush_to_disk` (previously only in `FilesystemRoot`)
- Refactor `FilesystemRoot.flush_to_disk` to use `FilesystemEntry.flush_to_disk`
- Rename `Resource.flush_to_disk` to the more accurate `Resource.flush_data_to_didsk` to indicate that it only flushes data, not any attributes
@EdwardLarson

Flush symbolic links and filesystem entries

---

docs/user-guide/advanced/patch-maker/user-guide.md
ofrak_core/CHANGELOG.md
ofrak_core/ofrak/gui/server.py
ofrak_core/test_ofrak/unit/test_ofrak_server.py

In PR #373, `Resource.flush_to_disk` was renamed to `Resource.flush_data_to_disk`. In that rename, I missed a couple of usages of the old `flush_to_disk` method. This PR fixes those stragglers.
@whyitfor

Rename two missed usages of Resource.flush_to_disk

---

ofrak_core/test_ofrak/unit/test_ofrak_server.py

These changes avoid unhelpful content-type errors in OFRAK testing code. They do not impact test functionality.
Update testing code to avoid unhelpful warnings on unexpected JSON content type.
N/A.
Testing code ignores these warnings to focus on actual test content.
@EdwardLarson

Disable content_type checking in OFRAK Server testing code.

---

disassemblers/ofrak_ghidra/ofrak_ghidra/components/ghidra_analyzer.py
disassemblers/ofrak_ghidra/ofrak_ghidra/components/identifiers.py
disassemblers/ofrak_ghidra/ofrak_ghidra/ghidra_model.py
disassemblers/ofrak_ghidra/ofrak_ghidra/ghidra_scripts/CreateMemoryBlocks.java
disassemblers/ofrak_ghidra/ofrak_ghidra_test/conftest.py
disassemblers/ofrak_ghidra/ofrak_ghidra_test/test_ghidra_program_analyzer.py
ofrak_patch_maker/ofrak_patch_maker/toolchain/gnu_vbcc_m68k.py

Add a Ghidra script to create a memory map for a binary, mirroring OFRAK's, when Ghidra cannot load the target binary itself.
Ghidra has loaders for some formats, but OFRAK has unpackers for some programs that Ghidra does not (e.g. Uimage). So although OFRAK unpacks these and can find the memory sections, Ghidra cannot analyze any of the code. It would be desirable for future formats as well, once an OFRAK unpacker is written, for them to automatically be supported by Ghidra (as best they can).
* Custom Ghidra "loader" that runs as a pre-script, creating memory blocks and marking code blocks
* Minor fix to m68k toolchain, some optimization …

Ghidra custom "loader"

---

.github/workflows/test-all.yml
.pre-commit-config.yaml
disassemblers/ofrak_ghidra/ofrak_ghidra/components/ghidra_analyzer.py
ofrak_io/setup.py
ofrak_type/setup.py

#323 attempted to bump black versions, but missed a few files.
Use black==23.3.0 throughout.
Relates to #323.

Bump black versions to be consistent with #323.

---

CONTRIBUTING.md
README.md
docs/index.md

**One sentence summary of this PR**
Fix broken Slack invite URLs in some of the documentation.

Fix Slack invite URLs

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/free_space.py

Fixes erroneous Free Space Modifier expectation that resource parents are memory views.
@whyitfor

Create free space when parent is not MemoryView

---

ofrak_core/CHANGELOG.md

I forgot a CHANGELOG entry update for #407 before I merged. This PR adds the overlooked changelog.

Add missed CHANGELOG for #407

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/free_space.py
ofrak_core/ofrak/gui/server.py
ofrak_core/test_ofrak/components/test_free_space.py

Change `FreeSpaceModifier` & `PartialFreeSpaceModifier` behavior: an optional stub that isn't free space can be provided and fill-bytes for free space can be specified. 
N/A.
This changes the signature and intended behavior of the configs for `FreeSpaceModifier` and `PartialFreeSpaceModifier`. Each modifier now allows for injecting a "stub" at the beginning of the targeted code to be freed. This stub is not included in the `FreeSpace`. The config's "fill" parameter is now the data pattern used to overwrite the bytes that fall in the `FreeSpace`.
@rbs-afflitto, @rbs-alexr.
Optionally: …

Modified the FreeSpaceModifier to mark patch bytes written to the binary as not free

---

ofrak_patch_maker/CHANGELOG.md
ofrak_patch_maker/ofrak_patch_maker/toolchain/abstract.py

We also want to drop the .altinstr_replacement section when we are performing patches
This PR adds .altinstr_replacement to the toolchain's linker section droplist
@rbs-afflitto also ran into this issue

Dropping the .altinstr_replacement section from the toolchain

---

frontend/public/global.css
ofrak_core/CHANGELOG.md

Set the fallback font to monospace.
@dannyp303

Set the fallback font to monospace

---

frontend/src/utils/StructuredList.svelte
ofrak_core/CHANGELOG.md

Display strings with numbers primarily as strings in the GUI attributes view.
@dannyp303

Display strings with numbers primarily as strings

---

disassemblers/ofrak_ghidra/CHANGELOG.md
disassemblers/ofrak_ghidra/setup.py

Just add typing support to the `ofrak_ghidra` package. This avoids getting errors from mypy like `error: Skipping analyzing "ofrak_ghidra": module is installed, but missing library stubs or py.typed marker`
Just add typing support to the `ofrak_ghidra` package.

Add typing support to ofrak_ghidra package

---

ofrak_core/test_ofrak/components/test_comments.py
ofrak_core/test_ofrak/unit/test_ofrak_context.py

Fix two tests that fail on occasion for [IMHO] no good reason.
N/A
Two tests would sometime fail for me:
- `ofrak_core/test_ofrak/components/test_comments.py::test_comment_content` had a default 200ms time limit, and once in a while, the limit would be violated (particularly, if other things happen to be running at the same time the tests run) - I have seem numbers as high as 1.6 s on occasion. I bumped the limit to 5s.
- `ofrak_core/test_ofrak/unit/test_ofrak_context.py::test_get_ofrak_context_over_time` would occasionally fail with the `RuntimeError: There is no current event loop in thread 'MainThread'` error message. I am guessing that …

Fix occasional spurious test failures.

---

build_image.py
disassemblers/ofrak_binary_ninja/Dockerstub
disassemblers/ofrak_ghidra/Dockerstub
frontend/Dockerstage
frontend/Dockerstub
ofrak_core/CHANGELOG.md
ofrak_tutorial/Dockerstub

- $PACKAGE_PATH generalizes build_image.py such that it works with any yaml file containing a valid list of Python packages
Before this change, it was possible to use build_image.py a directory above the OFRAK repository by passing in an OFRAK_DIR arugment in the yml file. This change generalizes the approach so that build_image.py can be run in any ancestor directory; it also removes the need to pass in an OFRAK_DIR argument.
N/A.
See above.
@rbs-jacob

Move away from $OFRAK_DIR argument to $PACKAGE_PATH for Docker builds

---

ofrak_patch_maker/CHANGELOG.md
ofrak_patch_maker/ofrak_patch_maker/toolchain/gnu.py

- Removed `SUBALIGN(0)` for `.bss` sections
- N/A
The `SUBALIGN(0)` option was leading to the following linker errors when building AARCH64 patches:
```
relocation truncated to fit: R_AARCH64_LDST64_ABS_LO12_NC against `.bss'
warning: one possible cause of this error is that the symbol is being referenced in the indicated code as if it
had a larger alignment than was declared where it was defined.
```
`SUBALIGN(0)` strips any alignment which is specified. It is not clear what issue was fixed by adding this originally. Future alignment issues should be fixed by setting the alignment of bss variables with the `__attribute__ ((aligned()))` …

Revert using SUBALIGN(0) for .bss sections

---

disassemblers/ofrak_ghidra/requirements.txt
frontend/backend/ofrak_server.Dockerfile
ofrak_core/requirements.txt

aiohttp <3.9.3 has known security issues:
- https://github.com/redballoonsecurity/ofrak/security/dependabot/12
- https://github.com/redballoonsecurity/ofrak/security/dependabot/11
- https://github.com/redballoonsecurity/ofrak/security/dependabot/18
- https://github.com/redballoonsecurity/ofrak/security/dependabot/17
- https://github.com/redballoonsecurity/ofrak/security/dependabot/16
- https://github.com/redballoonsecurity/ofrak/security/dependabot/15
- https://github.com/redballoonsecurity/ofrak/security/dependabot/10
- https://github.com/redballoonsecurity/ofrak/security/dependabot/9
See above.
This bumps aiohttp to ~=3.9.3
**Anyone you …

Bump aiohttp to ~=3.9.3

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/elf/lief_modifier.py
ofrak_core/test_ofrak/components/test_elf_modifiers.py

Add modifier to add and remove sections using lief. 

add lief add/remove section modifier

---

build_image.py

Creates an individual target in the root `Makefile` for each package's `make test`, with `test` depending on all of them
N/A
Creates an individual target in the root `Makefile` for each package's `make test`, with `test` depending on all of them. This has a number of advantages, the biggest (and my motivation) is that this way `make -k test` in the container root would run through all the packages, rather than stopping on the first one with errors.
Here is an example of the relevant section of `Makefile` created for `ofrak-core-dev.yml` with this change:
```
.PHONY: test test_ofrak_type test_ofrak_io test_ofrak_patch_maker test_ofrak_core …
```

Support `make -k test` in docker root

---

disassemblers/ofrak_binary_ninja/install_binary_ninja_headless_linux.sh

Explicitly set the Binary Ninja downloaded package file name, so that the installer script knows what to unzip.
https://github.com/redballoonsecurity/ofrak/issues/450
The Binary Ninja accepts an `--output` argument which sets the name of the downloaded Binary Ninja package. This PR uses that argument to set the output file name to `binaryninja-headless.zip`, so that the script knows what the downloaded .zip is named. This should work across platforms and prevent renaming issues from occurring in the future.
@whyitfor

Explicitly set the Binary Ninja package file name

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/apk.py

Support `application/vnd.android.package-archive` mime type for APKs, which is returned by newer versions of libmagic
N/A
In Debian 12 Bookworm with libmagic 5.44-3, `ofrak_core/test_ofrak/components/test_apk.py` currently fails, as the `ApkIdentifier` does not recognize the test apk file as such. The issue is that currently `ApkIdentifier` expects apks to be recognized by libmime as `application/java-archive` or `application/zip` but in fact it is recognized as `application/vnd.android.package-archive`. This change adds `application/vnd.android.package-archive` to `ApkIdentifier` - for that mime type, the `Apk` tag is immediately added …

Support `application/vnd.android.package-archive` mime type for APKs

---

ofrak_core/requirements-test.txt
ofrak_core/test_ofrak/components/test_patch_maker_component.py

Fix an issue with parallel tests potentially clashing
N/A
The `test_function_replacement_modifier` in `ofrak/ofrak_core/test_ofrak/components/test_patch_maker_component.py` is configured to run several times, sometimes writing the same `replaced_hello.out` program. When running tests in parallel, this can create spurious failures if two tests try to write the output binary at the same time. This change introduces an inter-process file lock to avoid this.
Not sure

Fix an issue with parallel tests potentially clashing

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/gzip.py

- [X ] I have reviewed the [OFRAK contributor guide](https://ofrak.com/docs/contributor-guide/getting-started.html) and attest that this pull request is in accordance with it.
Use GzipFile python unpacker for speed, fall back on pigz if needed
N/A
Back before OFRAK became public we switched to using external gzip, and then later in #79 we switched to pigz. The reason the initial switch to gzip was made is because unlike python gzip, gzip and pigz binaries are willing to accept gzipped data with extra junk at the end as a "warning" (exit code 2, as opposed to exit code 1 for errors). Unfortunately, spawning external processes has nontrivial …

Use GzipFile python unpacker for speed, fall back on pigz if needed

---

disassemblers/ofrak_ghidra/CHANGELOG.md
disassemblers/ofrak_ghidra/ofrak_ghidra/components/ghidra_analyzer.py

* Do not run Ghidra auto-analysis upon importing a program
N/A
This change adds `-noanalysis` to the import command in `_do_ghidra_import` in the `GhidraProjectAnalyzer`. Without this change, Ghidra analysis runs every time the `GhidraProjectAnalyzer` runs. This consumes a significant amount of time that is not necessary if using a pre-analyzed Ghidra project. By adding `-noanalysis` to the import command, the Ghidra analysis will run conditionally in `_do_ghidra_analyze_and_serve`, depending on if a pre-analyzed Ghidra project has been passed into the analyzer config.
@whyitfor @SamL98

Do not run Ghidra auto-analysis on import

---

ofrak_core/Makefile

`make develop` inside ofrak_core does not work without first running `npm install`. This adds `npm install` as a step.
@rbs-jacob

Add install step for gui

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/cli/ofrak_cli.py
ofrak_core/ofrak/ofrak_context.py

By default, the ofrak log is now `ofrak-YYYYMMDDhhmmss.log` rather than just `ofrak.log` and the name can be specified on the command line.
#311 
See summary
@whyitfor maybe?

Make the log file name configurable and include timestamp by default

---

ofrak_core/test_ofrak/components/test_patch_maker_component.py

Currently running the test suite (specifically `test_function_replacement_modifier`) pollutes the current directory with these output files which the developer has to clean up to get a clean working tree. This changes it to use pytest's [`tmp_path`](https://docs.pytest.org/en/7.3.x/how-to/tmp_path.html) fixture.
The output files from subsequent runs are saved in pytest's temporary directories like so instead of being overwritten:
```
ofrakdev@e9d35e42d66b:/workspaces/rbs-ofrak/ofrak$ cd /tmp/pytest-of-ofrakdev/pytest-
pytest-0/       pytest-1/       pytest-current/ 
ofrakdev@e9d35e42d66b:/workspaces/rbs-ofrak/ofrak$ cd /tmp/pytest-of-ofrakdev/pytest-1/
ofrakdev@e9d35e42d66b:/tmp/pytest-of-ofrakdev/pytest-1$ ls
test_function_replacement_modi0  test_function_replacement_modi2 …
```

Use temporary output directory for `test_function_replacement_modifier`

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/entropy/Makefile
ofrak_core/ofrak/core/entropy/entropy.c
ofrak_core/ofrak/core/entropy/entropy.py
ofrak_core/ofrak/core/entropy/entropy_c.py
ofrak_core/setup.py

Partially reverted [#150](https://github.com/redballoonsecurity/ofrak/pull/150) so entropy C code is called with `ctypes` again, but maintaining the current API and automatic compilation by `setup.py`.
Extends setuptools build_ext command to add a `.1` to the end of extensions marked with ctypes to match the old behavior. Not sure if this modification is still needed.
@jstrieb

Return to using `ctypes` for entropy calculation (partially reverts #150)

---

.github/workflows/test-all.yml

Remove workflow caching steps to fix GitHub Actions CI running out of space. The cache isn't really useful anyway – since PR #67, the Docker caching hasn't actually been used in GitHub Actions.
@whyitfor

Remove workflow caching steps

---

build_image.py

Added `SHELL` instruction to image building script to ensure consistent OS signal behavior
N/A
As `build_image.py` stands now, building images with `ENTRYPOINT`s including `&`, `&&`, etc leads to the following warning in the build log for `finish.Dockerfile`:
`WARN: JSONArgsRecommended: JSON arguments recommended for ENTRYPOINT to prevent unintended behavior related to OS signals`
Eg, when running `make tutorial-image`:
```
...
> importing cache manifest from redballoonsecurity/ofrak/tutorial-base:master:
------
[+] Building 0.5s (17/17) FINISHED …
```

Add SHELL instruction to avoid JSONArgsRecommended warning

---

ofrak_core/requirements-test.txt
ofrak_core/setup.py
ofrak_core/test_ofrak/components/test_patch_from_source.py
ofrak_core/test_ofrak/components/test_symbolic_analysis.py

Reverts redballoonsecurity/ofrak#420

Revert "Fix circular dependencies by making `ofrak_angr` and `ofrak_capstone` optional for `ofrak_core` tests"

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/service/serialization/serializers/class_instance_serializer.py

When `ComponentConfig` dataclasses have a field with a default value of `None`, the PJSON deserializer fails to deserialze the values. This fixes that bug.
@dannyp303

Fix component configs default field=None bug

---

examples/Makefile
examples/test_examples.py

Added test for example 9. Also enabled coverage report and enforced 100% function coverage for tests.
None
Modified Makefile to add coverage report and enforce 100% function coverage. Added test for example 9: check that the inserted string is in the modified flash dump and check that the md5 sum matches the expected value.
@whyitfor

Test example 9

---

build_image.py

Adds an optional `--image-revision` argument to `ofrak.yml` to support image revision tagging
when building an OFRAK docker image from a source bundle without git.
N/A
See above
@whyitfor

Do not try to get git revision when `image_version` tag exists in .yml

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/service/resource_service.py

Fix bug where calling `Resource.remove_tag` on both a tag class and a class that inherits from that class causes a `KeyError` on resource save.
#507 
Does not fully fix that issue, since calling `remove_tag` on _only_ the parent tag will not properly remove it.
Changes a call to `.remove` to `.discard` instead, since its possible the resource was already removed from the index in the same update cycle

Fix `KeyError` on resource save after calling `Resource.remove_tag` on parent and child tag class

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/patch_maker/modifiers.py

The src and header files that serve as input to `PatchFromSourceModifier` are now written to the same temporary
directory that PatchMaker uses for its output.
The src and header files that serve as input to `PatchFromSourceModifier` are now written to the same temporary
directory that PatchMaker uses for its output.
This will make it easier to compare BOM/FEM files to the source code that generated them
I've tested this change with an example from https://github.com/whyitfor/ofrak-u-boot, the temporary build directory now helpfully includes the source files:
```
/tmp/tmpbf6xisdn
├── do_version_patch_bom_files
│   ├── do_help.c.o
│   └── …
```

Update PatchFromSourceModifier to place src and header files in same temporary directory as BOM/FEM artifacts

---

ofrak_patch_maker/ofrak_patch_maker_test/test_symbol_parsing.py

This test was incorrectly marked as `async def` so it never actually run in CI or locally in my experience.
See example logs here: https://github.com/redballoonsecurity/ofrak/actions/runs/11921517683/job/33225804260#step:6:380
Maintenance only change
- Removes a spurious `async def` preventing this test case from running
- Renames the `TestCase` class so pytest doesn't think it's a class with tests
@whyitfor @rbs-jacob

Run `ofrak_patch_maker_test/test_symbol_parsing.py`

---

.github/workflows/test-all.yml
Makefile
build_image.py
docs/user-guide/disassembler-backends/binary_ninja.md

Default to forcing Docker buildkit to be enabled.
N/A; supersedes #392 
Per @EdwardLarson:
> Some features in the build require Docker buildkit to be enabled, and we say as much in the docs to build the image. However, this is a point of failure (for some reason I could not get the buildkit to be enabled in my machine) and a "gotcha" that can be removed entirely by just setting the Docker buildkit enabled in the subprocess we spin up to do the Docker build. In case there is a desire to specifically NOT use the buildkit, an option is added to not alter the subprocess environment at all (buildkit may or may not be enabled depending on user's …

Auto-enable Docker buildkit

---

disassemblers/ofrak_ghidra/requirements.txt
frontend/backend/ofrak_server.Dockerfile
ofrak_core/requirements.txt

Addresses dependabot: https://github.com/redballoonsecurity/ofrak/security/dependabot/30.
https://github.com/redballoonsecurity/ofrak/security/dependabot/30
Bump aiohttp to 3.10.11.

Bump aiohttp to 3.10.11

---

ofrak_core/CHANGELOG.md
ofrak_core/requirements.txt

Update pycryptography to 43.0.3.
https://github.com/redballoonsecurity/ofrak/security/dependabot/24
- Update pycryptography to 43.0.3.
- Update changelog to account for #522.
@rbs-jacob

Update pycryptography to 43.0.3

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/ihex.py
ofrak_core/requirements-non-pypi.txt
ofrak_core/requirements.txt

Use PyPI version of bincopy, bump to 20.0.0
N/A.
Use PyPI version of bincopy, bump to 20.0.0

Use PyPI version of bincopy, bump to 20.0.0

---

.github/workflows/test-all.yml

Pin GitHub Actions CI Ubuntu version instead of using `ubuntu-latest`.
- <https://github.com/actions/runner-images/issues/10636>
According to the issue linked above, the `ubuntu-latest` GitHub Actions images are being bumped from Ubuntu 22.04 to 24.04. They are rolling out the change, so some repos are seeing it before others. On [my fork of OFRAK](https://github.com/rbs-jacob/ofrak/actions/runs/12217517784) the GitHub Actions workflows are failing due to this version change, since they use Python 3.7 to run `build_image.py`.
To preemptively fix this in OFRAK, I have pinned the CI Ubuntu version to the current 22.04. We can also bump the …

Pin Ubuntu version

---

ofrak_patch_maker/CHANGELOG.md
ofrak_patch_maker/Dockerstub

Update patchmaker dockerstub to use mirror server for downloading the BCC toolchain.
Update patchmaker dockerstub to use mirror server for downloading the BCC toolchain.
Use a mirror server for the download of the BCC toolchain, because the original server sometimes bans our IP.
@whyitfor

Use mirror for BCC toolchain

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/cpio.py

I assume I commented this out to test something on Windows, and left it in accidentally
Fix unintentional ignoring of cpio errors introduced in [#486](https://github.com/redballoonsecurity/ofrak/pull/486)
@rbs-jacob

Revert unintended commenting out of lines in cpio.py from #486

---

disassemblers/ofrak_angr/Makefile
disassemblers/ofrak_binary_ninja/Makefile
disassemblers/ofrak_capstone/Makefile
disassemblers/ofrak_ghidra/Makefile
ofrak-core-dev.yml
ofrak_core/Makefile
ofrak_io/Makefile
ofrak_patch_maker/Makefile
ofrak_tutorial/Makefile
ofrak_type/Makefile

`setuptools` changes the way editable packages are installed in newer versions. See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for information.
The default format for newer packages causes issues such as directories in the current working directory being imported unintentionally over editable packages with the same name. See https://github.com/pypa/setuptools/issues/3557#issuecomment-1226027571 for discussion about this issue.
For now, I believe it makes sense to use the "legacy" editable install mode to avoid issues until the newer editable hooks format is mature and bug-free.
Add `--config-settings editable_mode=compat` to `make develop` pip command lines.
#552 …

Add `--config-settings editable_mode=compat` to `make develop` pip command lines

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/model/resource_model.py
ofrak_core/ofrak/resource.py
ofrak_core/test_ofrak/unit/test_data_attributes.py

Update `Data.Offset` such that its value is always the equivalent to a resource's start offset in the data root:
```
Range.from_size(Data.Offset, Data.Length) == await resource.get_data_range_within_root()
```
Before this change, the `Data` attribute was created with the data range of a parent resource, which was not always equal to the data root range.
During patching, however, the value of `Data` were updated to correspond to the root data range. This created inconsistencies when sorting by `Data`--for example, in the OFRAK GUI tree. 
`TestGrandchildrenDataAttributes` asserts that the behavior is correct.
**Anyone you think should look at …

Data.Offset refers to offset in data root

---

ofrak_patch_maker/Dockerstub

Remove crosstool-ng loading spinner output during docker build.
`crosstool-ng` is used to cross-compile the m68k toolchain in the patch maker Docker build. Unfortunately, there is no argument or flag (that I could find) to tell `ct-ng` to run without a loading spinner. Since the builds can take a long time, and since the spinner is output regardless of whether `ct-ng` runs in a TTY or not, the Docker logs (on GitHub Actions and locally) are polluted by thousands upon thousands of lines of loading spinner slashes. For an example [check out this insane test run output](https://github.com/redballoonsecurity/ofrak/actions/runs/12658836028/job/35276633644?pr=562). 
To solve …

Filter excessive crosstool-ng output

---

ofrak_core/test_ofrak/service/serialization_service/test_pjson.py

Fix pjson tests on newer python versions (>3.8)
#543 
- Fix draw strategy for `os.stat_result` so it returns an actual `stat_result` instead of a bare tuple. Fixes test failure on Python 3.9+
- Second minor bug: fix the ambiguous type hint test input to use the correct list-of-tuples serialization for `Dict`, so that the error is actually from the type hint being ambiguous and not from the improper serialization. 

Fix pjson tests on newer Python versions

---

ofrak_core/ofrak/service/data_service.py

Use `bytearray` internally in data service to reduce copying when patching
#551 
Small change to the internal `_DataRoot` class so it uses a `bytearray` to store data internally. Significantly speeds up patching modifications which previously required 2 entire copies of the entire root data for each modification.

Use bytearray internally in data service to reduce copying when patching

---

.github/pull_request_template.md
CONTRIBUTING.md

Update CHANGELOG guidelines and documentation in pull request templates.
<https://github.com/redballoonsecurity/ofrak/pull/569#issuecomment-2590646518>
@whyitfor

Update docs with more detailed CHANGELOG guidelines

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/free_space.py
ofrak_core/test_ofrak/components/test_free_space.py

Fix bug with resource data offset in free_space.py introduced in #505. (No changelog necessary, fixes a bug recently introduced)
- Fix a typo where `(await resource.get_data_range_within_parent()).start` was accidentally replaced with `(await parent.get_data_range_within_parent()).start` in `FreeSpaceModifier`
- Change the free space modifier tests to use a child memoryregion with non-zero offset to catch this bug in the future.

Fix bug with resource data offset in `FreeSpaceModifier` introduced in #505

---

ofrak_core/CHANGELOG.md
ofrak_core/ofrak/model/resource_model.py
ofrak_core/setup.py

Add an lru_cache to `ResourceAttributes.get_indexable_attributes`.
N/A.
`ResourceAttributes.get_indexable_attributes` is called every time a resource is created.
By applying this lru_cache, we ensure that the work behind this function is done once per type of `ResourceAttribute`.

Cache ResourceAttributes.get_indexable_attributes

---

disassemblers/ofrak_angr/CHANGELOG.md
disassemblers/ofrak_angr/ofrak_angr/components/angr_decompilation_analyzer.py
disassemblers/ofrak_angr/ofrak_angr_test/test_decompilation.py
disassemblers/ofrak_angr/setup.py
disassemblers/ofrak_ghidra/CHANGELOG.md
disassemblers/ofrak_ghidra/ofrak_ghidra/components/ghidra_decompilation_analyzer.py
disassemblers/ofrak_ghidra/ofrak_ghidra_test/test_decompilation.py
disassemblers/ofrak_ghidra/setup.py
frontend/package.json
frontend/src/App.svelte
frontend/src/views/ContentView.svelte
ofrak_core/CHANGELOG.md
ofrak_core/ofrak/core/decompilation.py
ofrak_core/setup.py

Remove the `DecompilationIdentifier`.
N/A.
OFRAK identifiers are [expensive](https://github.com/redballoonsecurity/ofrak/pull/492). This changeset removes the `DecompilationAnalyzer`, and updates the frontend code to display the decompilation tab for any ComplexBlock.
This functionally is the same as it was before.
@dannyp303 and @rbs-jacob

Remove DecompilationIdentifier, it is not needed!

---

disassemblers/ofrak_ghidra/CHANGELOG.md
disassemblers/ofrak_ghidra/ofrak_ghidra/components/ghidra_decompilation_analyzer.py
disassemblers/ofrak_ghidra/ofrak_ghidra/ghidra_scripts/GetDecompilation.java
disassemblers/ofrak_ghidra/setup.py

Handle escape (`\`) character in the JSON going from Java (Ghidra) to Python.
None
I noticed that when the decompilation output from Ghidra contained something like `printf("This is bob\'s key.")`, then the Python side would raise an exception: `json.decoder.JSONDecodeError: Invalid \escape: line ... column ... (char ...)` because of the `\` character. I added a case in the list of special chars we replace on both ends.
No

Handle escape character in json

---

build_image.py
frontend/Dockerstub
ofrak_core/Dockerstub
ofrak_patch_maker/Dockerstub

Use `python:3.9-slim-bookworm` image.
N/A
Update Dockerstubs to use base slim image (python:3.9-slim-bookworm) and install what tools are needed when they are needed.

Use slim docker image

---

frontend/src/views/DecompilationView.svelte
ofrak_core/CHANGELOG.md

When the user selects the "Decompilation" tab in the GUI, the pane is updated with the decompiled code automatically, without having to click "Analyze" first.
#636 
I updated the `DecompilationView` to analyze the selected resource if the `DecompilationAnalysis` is not yet available ([link](https://github.com/NicolaasWeideman/ofrak/blob/9b627060ac79682486851d7ddc6c02f96d0e3901/frontend/src/views/DecompilationView.svelte#L40)).
@rbs-jacob

Update GUI to generate decompilation when tab is selected
